### ISSUE TITLE
Trouver un prestataire pour les soirées

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#10]
Le but de ce prestataire sera de gérer l'installation du matériel et la location.
- Liste des prestataires trouvés
  - http://www.masterdj.fr/
  - http://www.tonightsound.com/
  - http://www.sonoconcept95.com/
  - http://www.surprize.fr/ (Concrete, Hors Série, Weather Music Festival)

**Comment by Uinelj** [comment]
- Tonight Sound sont très intéressants et proposent du bon matériel pour un prix correct. A contacter pour demander un partenariat.
- Surprize est un très gros acteur. On risque de se faire snobber mais il faut le tenter.
- Masterdj sont sympas et ont de l'XP avec des universités.
- Sonoconcept semble mort.

**Comment by AlexFourgs** [comment]
En attente du devis de décisions-acoustiques.

**Comment by AlexFourgs** [comment]
Je ferme ici avec le prestataires de la fac, qui nous donne l'avantage d'avoir un réduction de 40% et aucune caution :
- reflechi-son.fr
