### ISSUE TITLE
Préparer le stream.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#13]
Il nous faut une ou deux GoPro, et de quoi agencer tranquillement le stream.

**Comment by AlexFourgs** [comment]
En gros il faut :
- Une ou deux GoPro (demande de subvention ? Voir avec Décision-accoustique ?)
- Un (bon) ordinateur
- Un logiciel pour le stream (gestion caméra, ajout de bannière, etc...)
- Une personne qui gère le stream ( @akkes @Eresia ?)
- Une (bonne) connexion internet ^^

Il faudrait peut-être voir avec la filière de montage vidéo (ou je sais plus quoi) qu'il y a à la fac, peut-être pourrait-ils nous aider ?

**Comment by Eresia** [comment]
Pas de soucis pour gérer le stream au besoin. 
Pour la co Internet celle de la fac peut-être largement suffisante une fois qu'il n'y a plus personne. Sinon voir avec la DISI
Et pour le log, OBS permet tout ça non ?

**Comment by Uinelj** [comment]
OBS me semble tout à fait approprié. 

LA grosse question : Quelle plateforme d'hébergement ?

Il faudrait faire un test soon histoire de voir comment ça se passe, et penser au routage du son aussi.

**Comment by AlexFourgs** [comment]
Dailymotion apparemment s'en bat les couilles pour les droits, le bémol c'est que ça s'intègre pas à FB il me semble. 

Il faudra intégrer le stream sur notre site + notre facebook.
- **Contacter la DISI pour avoir une arrivé internet de qualité** @Eresia tu pourrais envoyer un petit mail stp ?

**Comment by akkes** [comment]
Penser à demander le droit aux artistes aussi! Éventuellement leurs conditions/rétributions

**Comment by Uinelj** [comment]
Yep. 

Il est peut-être un peu tard, mais on peut penser à s'allier à Dailymotion / TRAX pour avoir un live daily qui ne risque pas d'être shutdown. (cf. les 24h de mix de [Pardonnez-nous](https://www.facebook.com/pardonnez.nous/))

HS: @akkes tu deviens vraiment le legal nazi de cette asso 🗿

**Comment by AlexFourgs** [comment]
@Uinelj hmmm, ouai si tu veux, mais Square Sound m'a parlé de ces délires de droits, en gros faut payer (très chère)

**Comment by AlexFourgs** [comment]
J'y pense, si jamais au niveau de la demande de sub on a +/- 600€ de marge, on en rajoute une ?

**Comment by AlexFourgs** [comment]
Et voir avec la DISI pour avoir une connexion filaire oklm au niveau de la scène (tiré un cable ou j'en sais rien)

**Comment by AlexFourgs** [comment]
Connexion vu avec la DISI c'est bon. 
On a une webcam, je pense qu'il faut trouver deux autres caméras (GoPro si possible) et trouver quelqu'un pour gérer la mise en place et la maintenance du stream pendant la soirée.

**Comment by akkes** [comment]
et niveau droits ? 🗿

**Comment by AlexFourgs** [comment]
Pour le stream ? Ou pour la diffusion musicale ?

**Comment by akkes** [comment]
la diffusion musicale du stream
