### ISSUE TITLE
Cadence #1 : Trouver un lieu.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#14]
On a une contrainte de ~300 personnes.

On a pensé à : 
- Rotonde StMartin
- RDC StMartin
- RU

Impérativement étudier la faisabilite. Dans l'ordre : 
1. Voir le nombre maximum de gens accueillables.
2. Si ça passe, penser au layout et contacter DA, la sécurité et tout le tamtam.

**Comment by AlexFourgs** [comment]
Le rez de chaussé de St Martin semble tout à fait approprié ?

**Comment by Uinelj** [comment]
Sous réserve d'avoir le feu vert de la sécurité.

**Comment by AlexFourgs** [comment]
Certes, mais à St Martin je vois pas ou faire ça sinon.

**Comment by AlexFourgs** [comment]
Je close, c'est réglé on a pas le choix de toute manière.
