### ISSUE TITLE
Lineup Cadence #1

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#15]
Il nous faut trouver des artistes pour assurer la première Cadence. On a besoin d'artistes House/Deep-House.
- [TAOS (Pont Neuf Records)](https://www.facebook.com/taostheartofsounds/?fref=ts)  ✔️
- G'boï & JeanMi
- Marina Trench
- Duvi
- [Squaresound](http://www.squaresound.eu/) 
- [Victor Arnau (Chineurs de Paname) ?](https://www.facebook.com/victor.arnau?fref=ts)
- [Dko](https://www.facebook.com/D.KOrecords/)
- [Robsoul]()
- [John Jastszebski](https://soundcloud.com/john-jastszebski)
- [Voiron]()
- [Kosme]()~~

**Comment by arya-coding** [comment]
Merci pour la liste Julien ! Avant de les contacter, il faut voir combien de temps durera notre cadence, pour définir le nombre d'artiste et le temps qui lui est consacré.

EDIT : Après une discussion avec Alex, la cadence durerais de 20h00 à 2h00. Trois artistes serait envisageable. La liste me paraît donc raisonnable

**Comment by Uinelj** [comment]
Trois sets de 2h ça me semble très bien. On peut prévoir trois sets de 1h30 dans les faits, et ça nous laisse un peu de battement.

**Comment by Uinelj** [comment]
MAJ : Les mecs de SquareSound.

**Comment by AlexFourgs** [comment]
Faut envoyer un mail type à tous ces contacts rapidement, si on connait pas la programmation avant mi-octobre on est baisé pour les cachets artistes.

**Comment by arya-coding** [comment]
@AlexFourgs @Uinelj NON ! Ne jamais contacter l'intégralité des artistes et encore moins un mail type !!
Il faut prendre en considération l'artiste en personnalisant le message !
Enfin, si on contacte 8 artistes, que les 8 disent oui, on fait comment ? On dit à 4-5 que ce n'est pas possible car on a trouvé "Mieux" ?
Non, il faut contacter un par un et progressivement car sinon on prends le risque de ne pas se faire apprécier des artistes etc.

**Comment by Uinelj** [comment]
Pas de mails types, t'inquiète @aryus96. Je suis en contact avec la majorité des acteurs, et on voit bien évidemment un par un.

**Comment by Beat-nique** [comment]
TAOS me dit ce soir s'il peut être dispo.

**Comment by Beat-nique** [comment]
Sinon Duvi (cf Line up Cadence #2) peut être dispo très rapidement

**Comment by AlexFourgs** [comment]
Faut vraiment trouver une line-up rapidement, connaitre les cachets de chacun d'entre eux et pour finir le moyen de paiement (si on est employeur (bourbier) ou si on fait autrement).

Sachant que la date à changer, TAOS pourrait être possible ?

D.ko un peu trop gros pour un premier event.

John Jastszebski j'aime bien, c'est plutôt cool ce qu'il fait !

Squaresound pourquoi pas mais en warm up !

Pour moi ce serait cool d'avoir une lineup crescendo, on commence doucement avec un set posé et sympa, on attaque derrière avec du un peu plus lourd et on termine en faisant explosé la baraque (que ce soit pov lineup ou pov style).

Donc pourquoi pas :
1. Squaresound (1h30 / 20h-21h30)
2. TAOS (2h / 21h30 - 23h30)
3. John Jastszebski (2h30 / 23h30 - 02h)

**Comment by Uinelj** [comment]
Je plussoie la lineup mais j'ai peur que John coûte à balle ! 
Prophet au début c'est lourd parce que c'est house-y mais pas full house non plus :)
[Set concrete](https://www.mixcloud.com/djprophet23/point-carre-x-woodfloor-x-05-08-16-x-part-1/) @aryus96 ça devrait te plaire !

Par contre Jastszebski ça reste un peu minimal/micro non ? C'est pas un souci mais il faut voir si c'est en adéquation avec l'ambiance.

**Comment by AlexFourgs** [comment]
Ouai pas faux, mais j'aimerais bien une tête d'affiche :/
Tu proposes qui à la place ?

**Comment by Uinelj** [comment]
Gab nous avait proposé Duvi également. Mais pour la tête d'affiche il faut faire gaffe pour pas se cramer sur les cachets. J'update la liste quand je trouve des idées :)

**Comment by AlexFourgs** [comment]
Faut faire vite...

**Comment by Uinelj** [comment]
De toute façon tant qu'on à pas le rdv squaresound on peut rien faire..

**Comment by AlexFourgs** [comment]
@Uinelj pourquoi ? On peut toujours contacter les bookeurs des artistes qui nous intéressent pour avoir des idées concernant les cachets...

**Comment by Uinelj** [comment]
Donc : 

- TAOS
- Duvi
- GBoï et JeanMi
- Marina Trench

On a une plage horaire de 20h30 à 4h environ, ce qui fait pas mal.
On peut se dire qu'on commence le premier set à 21h, et que le dernier se finit à 3h30 (ça laisse un quart d'heure de rab quoi..)

- 21h - 22h30 : Duvi
- 22h30 - 00h00 : TAOS
- 00h00 - 02:00 : GBoï et JeanMi
- 02h00 - 03h30 : Marina Trench

**Comment by AlexFourgs** [comment]
Pour conclure :
Uj & Trême en warmup
TAOS
Marina Trench
G'Boï & Jean Mi
