### ISSUE TITLE
Contacter monte ta soirée concernant les drogues.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#16]
La personne a des contacts qui pourraient nous permettre d'XP un peu niveau dépistage de drogue.

**Comment by AlexFourgs** [comment]
Je met le mail qu'ils nous ont envoyés à ce sujet :

Bonjour à toutes et tous, 
Je vous envoie en pièce jointe le diaporama qui a été utilisé lors de la formation du 13 septembre dernier.

Les notes que nous avions pris pendant la formation figurent dans le document.

Concernant les questions relatives aux autres produits que l'alcool et notamment les stupéfiants qui peuvent être consommés par votre public, je vous invite à vous rapprocher de l'association Techno+. 
Vous pouvez notamment vous informer via les flyers qu'ils font sur chaque produit. Leur approche est une approche de réduction des risques "si tu consommes voilà ce que tu peux faire pour limiter les risques". Vous pouvez vous même télécharger et imprimer des flyers. Voici le lien : http://www.technoplus.org/t,1/2094/nos-flyers
Bonne réception,

**Comment by AlexFourgs** [comment]
cf #22
