### ISSUE TITLE
Acheter une webcam pour les cadences sauvages / afterwork ?

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#18]
J'ai pensé à investir dans une petite webcam afin de pouvoir proposer des petits Facebook Live de qualité lors d'événements à l'arrache, ie. cadences sauvages et d'afterworks.

Vous en pensez quoi ? @akkes @aryus96

**Comment by akkes** [comment]
## Cadences Sauvages

Un téléphone serai probablement mieux, ça renforce le coté "sauvage". Au moins mettre la webcam à la verticale. Pour pousser le délire faut aussi avoir un encodage moyen pour pas donner une impression "pro"

## Afterwork

Là on peut se permettre d'avoir une bonne qualité et un cadrage classique.

## Techno
- _Periscope_ est pas mal utilisé pour les lives mais il me semble qu'en dehors du milieux médiatique/twitter c'est pas très connu.
- _Facebook Live_ Déjà y'a Facebook dans le nom, ça peut pas être bien! 😝 Ça a l'avantage d'être dans Facebook et donc en "terrain connu" pour pas mal de monde (même si ils ne connaissent pas la fonctionnalité). Il me semble aussi que Facebook favorise les vidéos hébergés chez lui. Par contre ça compte les vues d'une manière dégueulasse (si t'as maté 3s d'un live t'es compté comme une vue). 

Pour les deux ce serai cool de voir à quel point la vidéo est extractible.

**Comment by arya-coding** [comment]
Je suis d'accord, mais pour le choix de la webcam juste un truc résistant et maniable, la qualité du stream sera de toute manière faible de part le support (Facebook) et les connexions qu'on utiliserais.

Le côté téléphone à l'arrache c'est pas bête, au pîre pendant l'event, le staff/fans/membres poste des petites vidéos sur la page !

**Comment by akkes** [comment]
Faudrait comparer le taux d'engagement des deux solutions (live ou petites vidéos) pour trancher je pense.

**Comment by Uinelj** [comment]
## Cadences sauvages

Je suis pas trop d'accord pour le téléphone : L'évènement est sauvage certes, mais faire du ghetto pour faire du ghetto... :) ! Là on peut aisément avoir un mini setup webcam + laptop + OBS qui nous permet d'avoir un stream correct. Concernant l'encodage, FBLive nique déjà bien la qualité de ton stream ! :)
Et le plus important, avec un laptop on pourra balancer le son directement depuis la table de mixage, ce qui est un GROS plus.

## Afterwork

Same.

## Techno

Je vote pour FB. Notre communauté est dessus, et on a une notification à chaque fois qu'on passe en live. De plus, on peut se faire RT par la vie asso !
