### ISSUE TITLE
Renommer le repo

### ISSUE THREAD

**Issue by akkes** [bdeecho/Chaudiere#19]
Histoire de ne pas avoir de confusion, ce serai cool d'avoir le repo qui a le nom de l'event non?

**Comment by Uinelj** [comment]
Bah je sais pas trop. On parle des Afterworks aussi ici.

**Comment by akkes** [comment]
Pour les afters, éventuellement les nommer "Cadences Light"?

**Comment by AlexFourgs** [comment]
Je close, on s'est mis d'accord sur :
- Cadence = Cadence + Apéro + Cadence Sauvage
