### ISSUE TITLE
Sponsoring / Partnerships

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#2]
Liste des sponsors / partenariats potentiels pour les Boiler :
- SonoVente
- PlanetSono
- Radio ?
- Marque de DJ ?
- Contacter _Music'os_ (Assoc' de musique) ?
- Général / Sponsors :
  - **Boiler Room** : contact@boilerroom.tv
  - **Combo95** : info@combo95.org
- Partenariat :
  - **SonoVente** : infos@sonovente.com

**Comment by Uinelj** [comment]
[Combo95](http://www.combo95.org/)

**Comment by AlexFourgs** [comment]
Ok, des marques sinon ? Si on arrive à récolté quelques fond en échange de mettre une bannière perso ça me dérange pas.

Boiler Room comme sponsor ? x)

**Comment by Uinelj** [comment]
ça me paraît être un peu forceur. Cela dit, cela peut être une bonne idée de les contacter, puisque on parle d'évènements assez similaires. J'ai peur un peu qu'ils nous bashent en nous disant que le concept est déjà existant blahblah. Il nous faut absolument résoudre #4 #3 et trouver un nom, histoire de venir leur parler avec un projet cohérent, s'ils ont besoin de plus d'infos.

**Comment by Uinelj** [comment]
Voir peut-être aussi avec des sponsors qui sont dans la mouvance et qui donnent facilement, genre Red Bull.

**Comment by AlexFourgs** [comment]
Ok, donc va falloir décider des dates assez rapidement, je suis justement entrain de chercher les événements electro à Paris, regarde sur Digitick, c'est la ou tu trouvera la majorité d'entre eux.

**Comment by Uinelj** [comment]
Il faut regarder également Resident Advisor.

**Comment by AlexFourgs** [comment]
A CONTACTER EN URGENCE ! Peux tu commencer un "mail type" stp ?

**Comment by Uinelj** [comment]
Yes.

**Comment by AlexFourgs** [comment]
Ou t'en est pour le mail ?

**Comment by arya-coding** [comment]
Sponsors culturels qui promeuvent le genre d’événement que nous souhaitons faire :

## Sûr
-  Nova LE GRAND MIX
- Les Inrocks
- Arte

## à tenter
- A NOUS PARIS  
- UGC
- Gaumont Pathé

**Comment by AlexFourgs** [comment]
Question à se reposer une fois le premier événement organisé.
