### ISSUE TITLE
Trouver une charte graphique aux événements cadence.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#20]
# Polices :
- https://fonts.google.com/specimen/Allerta+Stencil
- https://fonts.google.com/specimen/Bungee+Hairline
- https://fonts.google.com/specimen/Syncopate
- https://fonts.google.com/specimen/Quantico
- https://fonts.google.com/specimen/Six+Caps
- https://fonts.google.com/specimen/Black+Ops+One
- https://fonts.google.com/specimen/Monoton
- https://fonts.google.com/specimen/Audiowide
- https://fonts.google.com/specimen/Nova+Mono
- https://fonts.google.com/specimen/Graduate
- https://fonts.google.com/specimen/Sarpanch
- https://fonts.google.com/specimen/Jura
- http://fontsup.com/font/microgramma-d-ot-bold-extended.html
- https://www.fontsquirrel.com/fonts/exo
- https://www.fontsquirrel.com/fonts/Museo-Slab
- https://www.fontsquirrel.com/fonts/ChunkFive
- https://www.fontsquirrel.com/fonts/geometria

**Comment by akkes** [comment]
La question c'est: quelle image vous voulez donner à cadence?

**Comment by arya-coding** [comment]
J'ai sélectionne deux polices : 
Nova Mono
Jura

Mais en résultat, elles ne sont pas top.

J'ai réalisé quelques autres modèles, donnez vos impressions en utilisant les numéros afin que l'on sache du quel vous parlez.
(Perso, mes préférés sont 1 & 3)

## 1

![1](https://cloud.githubusercontent.com/assets/9800251/18632710/272ecc80-7e79-11e6-85a4-bb4f5c210db7.jpg)

## 2

![2](https://cloud.githubusercontent.com/assets/9800251/18632723/35378b5a-7e79-11e6-86a8-fdb83c910ab6.jpg)

## 3

![3](https://cloud.githubusercontent.com/assets/9800251/18632724/3812cdbc-7e79-11e6-98a2-8fc179220a59.jpg)

## 4

![4](https://cloud.githubusercontent.com/assets/9800251/18632731/3ffaa22a-7e79-11e6-9d40-915374df9da3.jpg)

## 5

![5](https://cloud.githubusercontent.com/assets/9800251/18632738/44378678-7e79-11e6-9396-b66a90fe81f8.jpg)

## 6

![6](https://cloud.githubusercontent.com/assets/9800251/18632745/46286c2c-7e79-11e6-8cd5-663fa3700ab0.jpg)

## 7

![7](https://cloud.githubusercontent.com/assets/9800251/18632747/47eb4462-7e79-11e6-89a3-9588cacbff08.jpg)

## 8

![8](https://cloud.githubusercontent.com/assets/9800251/18632748/49200728-7e79-11e6-9981-48f3103d79ca.jpg)

## 9

![9](https://cloud.githubusercontent.com/assets/9800251/18632752/4f28ca60-7e79-11e6-8378-173ecfa4ef2a.jpg)

## 10

![10](https://cloud.githubusercontent.com/assets/9800251/18632754/50686e94-7e79-11e6-9f32-ba242120744d.jpg)

## 11

![11](https://cloud.githubusercontent.com/assets/9800251/18632756/51af4430-7e79-11e6-926c-01b87e1c79d2.jpg)

**Comment by akkes** [comment]
@aryus96 tu peux me justifier tes choix de police?

**Comment by Uinelj** [comment]
En fait @aryus96 j'ai pris des polices assez "perchées" pour pouvoir l'utiliser en tant que logo ! Tu penses quoi de Audiowide ? Je trouve qu'elle fait très "house des années 2000", et en ça, ça nous distingue.

**Comment by Uinelj** [comment]
Pour répondre @akkes on voudrait avoir une image tout d'abord différente, pour pouvoir attirer l'oeil, mais ça c'est logique. Perso j'étais parti sur une esthétique à la concrete, donc avec des visuels un peu perchés et quelque chose de minimaliste. Mais j'ai vu cet EP de Popof et j'ai trouvé que la police faisait vraiment ressortir un côté éclectique. C'est ce côté éclectique que j'aimerais retrouver dans le logo cadence.

**Comment by arya-coding** [comment]
Pour les polices j'ai pris des trucs originaux.
Déjà c'est sur qu'on fait pas un autre logo, on va pas en faire 25, les gens seront perdus. Déjà que y'a celui de Versity

Ensuite, voilà le résultat avec Audiowide :

## 12

![12](https://cloud.githubusercontent.com/assets/9800251/18633190/5caebc24-7e7b-11e6-87ed-0159646fab68.jpg)

**Comment by akkes** [comment]
une police exprime quelque chose, c'est pas un truc que tu choisi "parce que ça rend bien":
1. On fait pas un truc littéraire ou histoirique
2. Ça exprime plus un coté informatique rétro que l'électronique. pas de rapport avec la musique
3. Je pense pas qu'on puisse dire que flashdance soit lié à la musique électronique
4. L'inclinaison exprime la vitesse. Le coté humaniste l'ambiance en étant sympa
5. On cherche pas à faire un truc de luxe. Y'a plus inspiré comme police helvétique
6. Voir 1. et 2.
7. La 5 en mieux inspiré
8. C'est pensé pour parler de voiture mais vu que certains albums de vielle électro l'utilisaient, justement pour son coté voiture, ça passe. Mais je doute que ce soit l'image que vous ayez envie de donner.
9. En quoi les cadences sont violentes?
10. Rapport avec la culture hip-hop? 
11. Éventuellement pour son coté hype/moderne et sans compromis
12. À shortlister amha

**Comment by Uinelj** [comment]
Merci @akkes ! En un peu moins pédant ça aurait été niquel ! 📏 

Donc la 12 tu trouves ça bien c'est ça ?

**Comment by Uinelj** [comment]
@aryus96 Merci beaucoup ! Ca donne quoi Audiowide avec juste la première lettre en capitale ?

**Comment by akkes** [comment]
@Uinelj J'irais pas jusqu'à valider dans l'immédiat, une comparaison avec d'autres polices intéressantes me semblant utile, mais je m'y opposerai pas.

(Si vous avez des cours de non-pédanterie je prends. Je me demande si je ne deviens pas pédant quand on me donne une réponse à coté de la plaque, tout du moins que je perçois comme telle. Vu que la version non-pédante est [là](https://github.com/bdeecho/Chaudiere/issues/20#issuecomment-247987668))

**Comment by AlexFourgs** [comment]
Pour ma part :
3, 5, 7, 11, 12

8 j'aime bien mais un peu trop moderne.
9 mais trop mainstream. Ca fais trop festival EDM mdr

**Comment by Uinelj** [comment]
5, 7 et 11 je les trouve bien trop génériques et passe-partout, alors que la 12 on a une esthétique particulière ! Il faudrait se décider dans pas trop trop longtemps :)

**Comment by AlexFourgs** [comment]
Ouai 12 est vraiment pas mal.

Un vote pourrait être intéressant.

**Comment by akkes** [comment]
Y'aurait moyen de savoir ce qu'on veut exprimer au travers du logo? C'est le critère n°1 il me semble non?

**Comment by arya-coding** [comment]
Un vote risque d'être improductif pour ce genre de décision, mais il reste intéressant de prendre l'avis d'un plus large public.
Le 12 me fait penser à des jeux vidéos FPS dans l'espace :|

**Comment by arya-coding** [comment]
## 13

Dans le même style

![electro](https://cloud.githubusercontent.com/assets/9800251/18932798/478b65e6-85d2-11e6-914a-4d3b375a0fae.jpg)

**Comment by clairengn** [comment]
Moi j'aime bien la 7, 9, 12 (toujours suivre l'instinct féminin) mdr

**Comment by Uinelj** [comment]
EDIT: Ajout de 4 polices.

**Comment by Uinelj** [comment]
Il faudrait qu'on se mettre rapidement d'accord sur la charte graphique des Cadences, histoire de pouvoir laisser @aryus96 travailler, et surtout de rallier nos différents projets cadences à cette charte graphique (Cadences sauvages, cadences gourmandes, décadences/apéros mix)..

**Comment by akkes** [comment]
Je viens de tomber sur [Venera](http://www.losttype.com/font/?name=venera) qui me parait cool.
![venera-banner](https://cloud.githubusercontent.com/assets/1679348/19278926/7a3bc28a-8fdf-11e6-9b26-3b3964fe69dd.jpg)

**Comment by Uinelj** [comment]
La question c'est : combien ça va nous coûter ?

**Comment by akkes** [comment]
Faut voir si c'est considéré comme commercial

EDIT: Elle ressemble à ça
![capture d ecran 2016-10-11 a 18 35 05](https://cloud.githubusercontent.com/assets/1679348/19279396/8c968422-8fe1-11e6-9e60-b3d372683c25.png)

**Comment by Beat-nique** [comment]
Putain les gars vous partez loin pour une histoire de police haha. Perso j'aime bien la 2. C'est pas très beau, ça fait cheap mais du coup ça fait passer le message "à la cool, on se prend pas la tête". Après bien sûr ça marche que si toute la charte graphique est dans le même esprit

**Comment by Uinelj** [comment]
En vrai on a des nazis de l'infographie dans le projet donc forcément... :D !

**Comment by arya-coding** [comment]
Franchement c'est pour ça que j'ai give-up le logo cadence. Je sais que y'aura forcément quelqu'un de pas d'accord/satisfait dans l'histoire, alors en plus, si c'est dit de manière pédante et hautaine...

**Comment by Uinelj** [comment]
Il va falloir se décider quand même :) ! J'aime bien la font de @akkes

**Comment by AlexFourgs** [comment]
La 12 est la seule à avoir intéressée 3 personnes. 

Aucune autre font n'a fais plus de 2.

**Comment by AlexFourgs** [comment]
Bon, on va mettre fin au débat.

On choisis une Police d'ici Dimanche (Lundi GRAND maximum).

**Comment by akkes** [comment]
J'avais pris Venera pour la demande de sub. Je sais pas qui a fait la bannière de la première Décadence mais il me semble que c'est la même.

**Comment by AlexFourgs** [comment]
Go pour venera du coup
