### ISSUE TITLE
Préventions

### ISSUE THREAD

**Issue by akkes** [bdeecho/Chaudiere#22]
# Préventions

Cette issue a pour but de regrouper toute les préventions possibles sur nos events ainsi que les solutions possible.
## Sujet
- Abus d'alcool
- Drogue(s)
- Son trop fort
## Solution
- Son

Vu que la musique risque d'être forte ça pourrai être cool de faire de la prévention sur les risque. Éventuellement distribuer des [bouchons d'oreilles](https://www.amazon.fr/Ear-Classic-Lot-100-Paires/dp/B00I16YWJU/ref=sr_1_11?ie=UTF8&qid=1474124639&sr=8-11&keywords=bouchon+d%27oreille)

**Comment by AlexFourgs** [comment]
Je renomme l'issue "Prévention" afin qu'on liste toutes les préventions qui vont être fait sur nos events.
Ne t'inquiète pas, on y avait pensé :)

HS: Pas étonnant que ce soit toi qui fait la remarque sur le son trop fort :heart:

**Comment by Uinelj** [comment]
Related : #12

**Comment by arya-coding** [comment]
Feu, il faut des extincteurs.

**Comment by AlexFourgs** [comment]
@aryus96 haha, c'est pas vraiment le sujet ici, on parle pas de la sécurité mais vraiment de la prévention qui sera fait sur nos événements à l'aide de stands, et de distribution de choses en tout genre (Alcotest, Bouchons d'oreilles, etc...).
Tout ce qui est sécurité en soit c'est pas à nous de le gérer mais la sécu incendie de la fac je pense.

**Comment by AlexFourgs** [comment]
Pour relancer le sujet :
- On compte faire de la distribution GRATUITE de bouchons d'oreilles, ça coûte quedal, pour 50€ on en a 400.
- Il faudra acheter des éthylotest, la c'est plus chère par contre, mais faut voir la quantité. Si on prend un éthylotest par personne, en gros on est à 1€ par éthylo en moyenne, soit 400€.
- En général (drogue + alcool + sécu routière), y'a pas mal de service qui vend des kits de flyers, mais ce qui pourrait être réellement intéressant c'est d'avoir 2 stands avec des gens qui te parlent de tout ça.

**Comment by Uinelj** [comment]
400 éthylo ça me semble être beaucoup ! On pourrait voir si on ne peut pas en louer un permanent, ou alors en prendre un peu moins ?

Après les éthylo c'est un achat qui : 
- Se rembourse si on fait payer l'éthylo 1€
- Périme pas et est balançable pour notre prochain event.

**Comment by AlexFourgs** [comment]
Quel intérêt de faire de la prévention en vendant un éthylo, c'est contre productif...

En gros sur le site de l'association de la prévention routière et des risques de l'alcool, ils mettent à dispo un kit pour 200 personnes et ils comptent 50 éthylo dedans. Si on part sur la même logique, on a besoin de 100 éthylo

**Comment by Uinelj** [comment]
L'intérêt c'est que ça coûte de l'argent aussi quand même..
En général les ethylo de boîte c'est 2€. Là avec 1€ on est déjà gentils je trouve ! 

On n'a pas de critères de rentabilité, mais si on peut économiser quelques centaines d'euro par ci par là, pourquoi pas.

**Comment by arya-coding** [comment]
Pourquoi partez vous du principe que tout le monde va venir en voiture ?
On pourrait aussi faire la promotion des services de taxi, G7, Heetch, Uber pour rentrer en sécurité !

**Comment by Uinelj** [comment]
Heetch serait très intéressant. Il faudrait les contacter.

**Comment by AlexFourgs** [comment]
Heetch c'est intéressant mais c'est pas des chauffeurs, question sécurité c'est pas top. C'est cool parce que c'est pas chère, mais mieux vaut prendre Uber comme partenaire de l'event.

@aryus96 oui oui tkt, on a revu à la baisse les éthylo et on peut les avoir gratos.

**Comment by arya-coding** [comment]
Ouaip mais heetch n'est pas à écarter, car peu cher et c'est toujours mieux que de rentrer bourré dans son propre véhicule Mdr

**Comment by clairengn** [comment]
Au niveau du son, vu qu'il y a de grandes vitres en verre, est ce que nous avons une limite de décibels à ne pas dépasser ? (cas déjà vu à une soirée au Grand Palais, le son n'était pas fort du tout, et les basses quasi inexistantes) 

Dans ce cas il serait intéressant d'avoir un sonomètre, et pour le local aussi par la même occasion.

**Comment by AlexFourgs** [comment]
Le service hygiène et sécurité nous indiquerons ce genre d'info, même si je pense que les vitre sont au moins du triple vitrage ce qui devrait pas poser de problème. 
Le sonomètre sera sûrement prévu par notre prestataire, et dans le cas contraire je sais que le service hygiène et sécurité en a un à disposition

**Comment by akkes** [comment]
Du coup c'est surtout la limite qu'il faut penser à demander à la sécurité

**Comment by AlexFourgs** [comment]
Tout cela sera vu lors de la réunion technique organisé avec l'ensemble des acteurs (vie asso, vie culturel, hygiène et sécurité)

**Comment by Uinelj** [comment]
Contacter la [Croix-Rouge Française](http://www.118000.fr/e_C0001060967#Hqyqv45SEsU0uTT5.99)

> Croix Rouge Française
> 10 RUE PETIT DE COUPRAY
> 95300 PONTOISE

**Comment by AlexFourgs** [comment]
Quelqu'un pourrait faire un récap' des choses à acheter / obtenir pour la soirée (bouchon, ethylo, etc...) qu'on les rajoute dans la demande de subvention si nécessaire.

**Comment by AlexFourgs** [comment]
Ça en est ou pour la croix rouge ? On a plus qu'une semaine pour fournir un devis si jamais on doit payer quelque chose pour eux.

**Comment by Uinelj** [comment]
Je m'en occupe cet après-midi.

**Comment by Uinelj** [comment]
Envoyer un mail à dlus95@yahoo.fr avec des infos pratiques.

**Comment by AlexFourgs** [comment]
Remplir la fiche envoyé par mail de la croix rouge et leur renvoyer.

[demande DPS 2016.pdf](https://github.com/bdeecho/Chaudiere/files/557920/demande.DPS.2016.pdf)

**Comment by AlexFourgs** [comment]
On a reçu un mail de "avenir-santé" ce matin qui propose d'intervenir sur les événements festifs avec des stands, distributions de capotes, ethylo, tracts et bouchons d'oreilles.

Je les ai contacté. En attente de leur réponse.

**Comment by AlexFourgs** [comment]
Avenir-Santé à contacter une fois la nouvelle date décidée.

**Comment by AlexFourgs** [comment]
Avenir-santé contactée.

**Comment by Uinelj** [comment]
J'ai les infos manquantes pour la croix-rouge, mais au vu des derniers détails techniques et du laps de temps qu'on à, je préfère delay un peu histoire de pas avoir à corriger maintes fois le dossier.

**Comment by AlexFourgs** [comment]
Ouai mais il faut qu'on ajoute le devis de la croix rouge à la demande de subvention.

**Comment by Uinelj** [comment]
Ok. Dans ce cas là je leur envoie un dossier dans la semaine en leur précisant que c'est vraiment pour un devis.

**Comment by AlexFourgs** [comment]
J'ai un rdv avec avenir-santé d'ici peu de temps.

**Comment by akkes** [comment]
du coup, y'auras quoi?
