### ISSUE TITLE
Organiser et préparer le bar.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#23]
Cette issue rassemble le travail préparatif à la tenue du bar. 

Ce travail comprend : 
- Acquisition d'une Licence 2
- Trouver une solution de location des tireuses
- Dimmensionner
- Trouver le fournisseur de tise, softs et eau.
- Staff ?

**Comment by Uinelj** [comment]
Voir [Barnum](http://www.barnum.fr/)

**Comment by AlexFourgs** [comment]
Barnum permet de louer des tireuses de plusieurs dimensions et d'acheter les fûts avec un large choix de bières.

Pour les softs je pense que le mieux reste de demander le numéro Siret ainsi qu'une carte Métro.

Reste le problème des fontaines à eau, soit on décide d'en installer quelques une, soit on donne au bar mais c'est de la gestion en plus.

**Comment by AlexFourgs** [comment]
On a oublié d'aller demander la licence 2. On attend la réunion technique, afin d'être sûr que l'événement se fera ?

**Comment by Uinelj** [comment]
Du coup concernant les softs on laisse Barnum s'en occuper ou on reste sur la carte Metro ?

On devrait attendre la réunion technique à mon avis.

**Comment by AlexFourgs** [comment]
Bah tant qu'à faire, autant laisser Barnum gérer ? Comme ça ils nous livrent tout puis c'est réglé. Si on passe par Métro faudra faire un devis à part, demander un Siret (ça prend du temps) et ensuite demander la carte Métro. Puis faudra surtout aller chercher toute les bouteilles, perso j'ai pas de camion lol

Après ça coûte rien d'aller tout de même voir les prix plus tard ?

D'ailleurs, pour la bière on a dis 20 fûts soit 1.7L par personne.

Pour les softs on prend combien ? Moi je m'étais dis 1 bouteille pour 3 personnes soit 0.5L de soft par personne, mais en comparaison avec la bière ça fais pitié, et puis l'event dure 6h.

**Comment by Uinelj** [comment]
Je ne sais pas trop. Je serais tenté de prendre une bouteille pour deux voire deux bouteilles pour trois. Il faudra vraiment savoir dimensionner correctement. Barnum n'a pas une idée ?

**Comment by AlexFourgs** [comment]
Humm, ou voir avec les autres associations ?

**Comment by AlexFourgs** [comment]
## Alcool & boissons (Barnum)
- **Caution de 1000€**
- **Acompte de 30%**
- Forfait Gaz CO2 : 30,00 € ht / 36,00 € ttc
- COMPTOIR de Service Inox pliable KLAPPOBAR L 150 cm - Location/Installation : Offert
- Possibilité de livraison et reprise : Forfait de 62,00 € ht / 74.4 € ttc (prix pour livraison et reprise en semaine)
- GOBELETS PP Lisse 25 cl (x 80) : 3.30€ ht / 3.96€ ttc

### Alcool
- Meuble Pression FESTIVAL 2 colonnes - Location / Installation : 145€ ht /174€ ttc [Offert à partir de 10 fûts consommés]
- Fût HEINEKEN 30 Litres : 112.50 € ht / 135 € ttc
- Fût 1664 Premium 30 Litres : 112.5 € ht / 135 € ttc
- Fût LEFFE Abbaye 30 Litres : 129,80 € ht / 155.76 € ttc
- Fût AFFLIGEM Abbaye 30 Litres : 129,80 € ht / 155.76 € ttc
- Version 1 :
  - 2*Meuble Pression FESTIVAL
  - 20*Fût HEINEKEN
  - Livraison / Récupération
  - 3 ou 4 comptoirs
  - **3194.4€ TTC** sans les softs (prix variable suivant le nombre de fût consommé)
  - **Acompte de 958.3€ sans les softs**
  - **Bénéfice possible (4€ la pinte et si les 20 fûts sont consommés) : 1953.6€** (auquel il faut enlever le prix des softs vu que ce sera open soft) 

### Softs
- Barnum s'en occupe aussi.
- Demander pour l'eau
- Bac à glace pour sacs 20kg : 5.90€
- **PAS DE FONTAINE À EAU**

**Comment by AlexFourgs** [comment]
D'après Antoine, 2 bouteilles de 2L par personnes pour voir large (soit 1L par personne, 350L de softs).

Pour les softs :
- Coca
- Ice Tea
- 7up Mojito
- Eau (on peut prendre des bidons de 8L comme au local, ça coûte 2€)

Vous en pensez quoi ?

**Comment by AlexFourgs** [comment]
On divise à part égale les softs ?

**Comment by AlexFourgs** [comment]
Du coup, si on change le nombre de slots, je vais préparer deux commandes, une pour 350 personnes, et l'autre pour 300.

**Comment by Najentun** [comment]
Ils pourrait être intéressant de mettre en place un système de jetons pour les conso pour une meilleur fluidité au bar car il n’y aura pas de caisse a gérer ,mais cela implique un coût  supplémentaire.
Sur le site https://fr.orakel.com ,les 1000 blanc sans aucune inscription coût 64€,soit pas grace chose,
de plus on peut les pimp avec logo et inscription.

**Comment by Uinelj** [comment]
A voir pour un prochain événement . Mais on planche sur des prix qui posent pas de problème au niveau de la monnaie (4€/pinte, 2€50/demi).

Mais dans l'instant ça me semble être relativement overkill, surtout qu'on a _que_ 300 personnes à servir.

**Comment by AlexFourgs** [comment]
Du coup :
- Bières :
  - 2 meubles Festival 
  - 17 fûts de Heineken (1.7L par personne)
- Softs :
  - 100L Coca
  - 100L Ice Tea
  - 100L 7up Mojito
- Divers :
  - 1200 Gobelets 50cl
  - Bac à glaces
  - 4 Comptoirs
  - Forfait gaz
  - Glace
  - Livraison / Récupération

Merci de me confirmer et de préciser si j'ai oublié quelque chose pour que je puisse demander le devis au plus vite à Barnum.

**Comment by Uinelj** [comment]
Je ne vois rien qui manque, pour moi c'est 👍

**Comment by AlexFourgs** [comment]
J'envoi le mail ce soir !

**Comment by AlexFourgs** [comment]
Il faut faire la demande de licence rapidement.

**Comment by Uinelj** [comment]
Aujourd'hui c'est impossible pour moi. Demain ?

**Comment by AlexFourgs** [comment]
Pas de soucis, moi non plus je peux pas aujourd'hui.

**Comment by AlexFourgs** [comment]
Je propose d'aller à la mairie demain (Mardi 25 Octobre) après-midi étant donné que le CM de IE est annulé.
Les demandes à faire sont les suivantes :
- Demande de Licence.
- Demande de barrière.
- Demande d'autorisation de stationner sur le terre-plein de l'avenue.

Certaines demande ne concerne pas le bar, je met en lien ici dans les issues correspondantes.

**Comment by AlexFourgs** [comment]
Demande de licence de débit de boissons 2 effectuées à la mairie de Pontoise. 

**En attente de leur retour pour aller chercher la licence**

**Comment by AlexFourgs** [comment]
Refaire une demande de licence pour le 10 février.

**Comment by Uinelj** [comment]
La licence pour le 16 a été révoquée ?

**Comment by AlexFourgs** [comment]
Non, je vais appeler la mairie je pense, ou y aller pour annuler et faire la demande pour la nouvelle en même temps.

**Comment by AlexFourgs** [comment]
* Demande d'un nouveau devis pour 430 personnes envoyé 
* Demande changement de date sur le devis initiale envoyé
* Demande nombre de comptoir offert

**Il faut refaire une demande de licence à la mairie de Pontoise**

**Comment by AlexFourgs** [comment]
Du coup, après la remarque de certaines connaissances, ils m'ont dis que QUE de la bière ça pouvait poser problème (en l’occurrence pour les filles qui sont pas trop bière en général) et on m'a conseillé de mettre du rosé aussi, qu'en pensait vous ?
