### ISSUE TITLE
Billetterie

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#24]
Trouver un moyen d'encaisser tranquillement.

**Comment by AlexFourgs** [comment]
- Weezevent (https://www.weezevent.com/)
  - Prend 0.99€ par billet, ce qui fait qu'on a 4.01€ dans les caisses d'Echo par billet. Soit 1203€ au lieu de 1500 si on vent les 300 billets sur la billetterie en ligne. On peut aussi bien augmenter le tarif à 5.99 pour payer les frais, et dans ce cas vendre les billets adhérents au local à 5€.

**Comment by Eresia** [comment]
Du coups vous n'utilisez pas Studeal ? Parce qu'ils gèrent ça

**Comment by AlexFourgs** [comment]
J'irais voir Studeal, mais je préfère utiliser un site spécialisé dans la billeterie, ça fait plus pro.

**Comment by Eresia** [comment]
Bof. Surtout si c'est pour perdre 1/5 de chaque inscriptions...

**Comment by AlexFourgs** [comment]
@Eresia, je suis d'accord avec toi, mais le problème de mon point de vue c'est que si tu met en place une billetterie sur un site qui ne sert pas qu'à ça, j'ai peur que les étudiants soient pas confiant.

La ou je veux en venir, c'est qu'un site qui a vraiment pour but d'être une billetterie et uniquement ça, ça inspire plus de confiance et ça fais plus pro. Cela reste un point de vue personnel, faudrait voir ce que chacun pense.

**Comment by Eresia** [comment]
C'est pas faux

**Comment by AlexFourgs** [comment]
Voila un petit test pour la billetterie de weezevent.
On peut intégrer un module sur notre site gratuitement pour vendre les billets et tout donc c'est plutôt cool. Je vous invite à regarder sur le site tout le côté gestion etc... ça va vraiment nous simplifier la vie si on utilise ce site je pense.

**Comment by AlexFourgs** [comment]
![pdf-202050_fr_0_0_0](https://cloud.githubusercontent.com/assets/15659639/18882442/780aa54a-84df-11e6-8aaa-db304b8165a2.jpg)

Voila les billets au final (test). Weezevent nous permet aussi de gérer la vente au local !

**Comment by AlexFourgs** [comment]
http://www.guitare-en-scene.com/index.php/fr/billetterie/conditions-de-vente

J'ai trouvé ça comme exemple de conditions de ventes qui est pas mal, ils prennent en compte le droit à l'image et d'autres détails. On pourrait s'en inspirer.

**Comment by Uinelj** [comment]
On verrouille Weezevent ?

**Comment by AlexFourgs** [comment]
Weezevent ou studeal, as you want !
Je vais faire un test de studeal ce soir pour voir si la prestation est équivalente.

**Comment by AlexFourgs** [comment]
On est d'accord sur studeal finalement ?

**Comment by Uinelj** [comment]
Yes, Studeal masterrace !

**Comment by AlexFourgs** [comment]
La billetterie se fera donc sur Studeal.

Je close.
