### ISSUE TITLE
Faire la demande de subvention.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#26]
# Demande de subventions

https://github.com/bdeecho/Chaudiere/blob/master/Cadence-1/demande_subvention_fsdiefave%20cadence%201%20340%20personnes%20hall.odt
 

## à voir lors de la prochaine réunion technique mais à laisser tout de même dans la demande :
* Astreinte électrique
* Matériel balisage de même

Ces locations ne seront peut-être pas à effectuer, nous verrons cela lors de la prochaine réunion technique début décembre mais nous les laissons tout de même dans la demande de subvention.

## à adapter :
* Sonorisation (demander les 40%)

## à ajouter :
* Devis T-SHIRT fait par madeinensea
* En attente du devis pour le gardiennage
* **Trouver une lineup avec les cachets par artiste**
* Croix rouge

**Comment by AlexFourgs** [comment]
@Uinelj Gilles s'occupe uniquement de la sonorisation et du matos DJ ou il gère aussi la lumière par exemple ? Ou encore le stand du DJ ?

**Comment by AlexFourgs** [comment]
@aryus96 pour la décoration, énumère tes idées, on a besoin de toi et de ton abus. Limite si t'a une idée d'ambiance à créer ça peut être sympa aussi !
Un point que j'ai oublié, la communication, affiches, tract, autocollant pendant la soirée, je te laisse gérer ça ? De nous faire le devis.

**Comment by ghost** [comment]
Uniforme + lampe torche de poche + Des bouteilles deau et des barres sucrees pour l'équipe encadrante?

**Comment by AlexFourgs** [comment]
Uniforme c'est-à-dire ?
On a parlé de Talkie Walkie hier avec @Uinelj aussi ;)
Mais c'est vrai qu'il faut penser au staff ! La lampe torche servirait à quoi aussi ?

**Comment by ghost** [comment]
Uniforme —> un element reconnaissable (habit/casquette) pour que les invités sachent qui contacter si il ya un probleme ou une question. 
Lampe torche —> meme si il yaura des lumieres d'effet, au cas ou il ya de la casse par terre (verre, equipement) ou quelqun se sent pas bien et/ou tombe, pour se deplacer rapidement dans le noir sans alumer toutes les lumieres, bref dans tous ces cas la une petite lampe torche a 10€ pour le staff est bien pratique. Ca evite de bousiller lambiance pour tous le monde en allumant la lumiere, tu vois le delire.

**Comment by AlexFourgs** [comment]
Uniforme -> Des t-shirts sont prévus, mais merci de le souligner j'ai oublié de le mettre dans le devis.
Lampe Torche -> Faudrait en discuté, sachant que y'aura la croix rouge et le service de sécurité je suis pas sûr qu'on en est réellement besoin mais pourquoi pas.

**Comment by arya-coding** [comment]
Je suis d'accord avec l'idée de Johan sur la lampe torche. Au moins une personne du staff sur deux, et on se la passe.
Ca peux toujours servir !

**Comment by arya-coding** [comment]
Cher collègues, camarades et DJ.

Voici les premiers devis 👍 
(J'ai la flemme de relire et corriger les erreurs, désolé.)

## Devis Com Cadence #1

On commence par la com' de l'event (Y'a un article extra).

![caaaaaaapture](https://cloud.githubusercontent.com/assets/9800251/18930849/005a2e80-85ca-11e6-8c87-729048c06374.PNG)

On part sur 1000flyers car au final le flyers c'est bien mais a distribuer et l'impact est bof, la preuve ? La soirée d'intégration, je n'ai pas vu de tract, les affiches ont suffit.

Par contre, affiche, grand format ! On est sur un 70cm sur 1 METRE, donc bien plus grande que les affiches "classiques", de nombreuses affiches également ! (Il faudra acheter du bon scotch).

On devra en coller PARTOUT !
Enfin le produit en extra, à en discuter mais c'est pour y mettre le logo CADENCE et qu'on utiliserait pour les mixs etc, à mettre sur les côtés du matos etc. Comme ca, tu te balades, au loin tu vois le drapeau, tu tilte direct et ca donne un côté pro et de la visu.

## Déco de la cadence #1

Maintenant, la décoration de l'évent :

![azecapture](https://cloud.githubusercontent.com/assets/9800251/18931425/693e4b3c-85cc-11e6-861c-1380791466c0.PNG)

Un côté exotique est intéressant car il fait voyager directement, et casse totalement le contexte la fac.
D'où les bambous, bananiers et palmiers.

Des colonnes lumineuses par ci par là. (3 tailles différents qu'on mets à côté).
Quelques manges debout pour les rencontres mn frr.

Bannissez les tables de cours, ca fait scolaire, gamin, enfant, on veux pas donner cette image !
Le bar, c'est important ! On va faire du biff, et c'est quand même BIEN plus cool que des tables étudiantes !
Un comptoir d’accueil pour les entrés, ca fait beaucoup plus pros.

Et la déco au sol ou au plafond, le décorer c'est pas mal à l'entrée, mais ensuite ça sert pas à grand chose. Genre quand tu rentres, tu regardes autour de toi, tu découvres, mais après quand t'es dans le vif, dans la soirée, tu ne prêtes pas attention. En plus c'est galère à trouver et à mettre en place :/.
Mais si vous trouvez qqlchose de cool à mettre au plafond dans les 1ers mètre de l'entrée, je suis partant

**Comment by AlexFourgs** [comment]
Beau travail !
- Communication :
  - pour les affiches, 150 ne serait pas suffisant ? Parce qu'on parle d'un event de 300 personnes.
  - Les flyers très bien, 1000 pour 50€ c'est donnée.
  - Les drapeaux ça me plait, mais il en faudrait un général, genre qu'on en rachète pas pour chaque cadence.
- Décoration
  Je kiffe le côté exotique perso mais 2000€ mdr, va falloir en enlever quand même.
  - Bambou 6 suffirait à l'entrée de l'event en intérieur pour créer une sorte de couloir
  - Bananier 2 pour la régie DJ (aux extrémités)
  - Les colonnes lumineuses pourquoi pas, à savoir ou on les posent (sécurité et tout)
  - Comptoir d'accueil pas la peine, une table suffira amplement surtout à ce prix !
  - Palmier 2 pour le bar ce serait cool.
  - Mange debout parfait, mais éventuellement en prendre même peut-être 6 à caler un peu partout dans le hall pour les gens qui veulent se poser un peu
  - Bar comptoir pas la peine, Barnum s'occupe de nous fournir des comptoir pour le bar

Très beau travail, juste revoir un peu à la baisse la majorité des choses. Pensé à des nappes pour les tables, et peut-être des nappes de plafond pour changer un peu le lieu et surtout mieux faire ressortir les lumières.

**Comment by arya-coding** [comment]
Merci pour les commentaires intéressants !

Affiches : C'est soit 100 soit 200, la différence entre les deux étant de 4-5€. Il vaut mieux s'assurer d'avoir assez de visibilité, surtout pour 5€. (200 c'est beaucoup quand même aussi).
Flyers : OK
Drapeaux : Oui, seulement le logo de cadence je pense.

Ok pour réduire le nombre d'arbre, mais il en faut quand même dans la salle pour moi. Pour créer une ambiance différente.

C'est vrai que pour le prix du comptoir d'entrée...
Ok pour le comptoir bar, pas besoin, on mettra des arbustes.

En effet, j'avais oublié les nappes pour les tables.
Oui, cela peut être facilement réalisable (et peu cher) pour des nappes sur le plafond, qu'on scotcherais. J'aime bien l'idée.

Je ferais d'ici peu un devis avec les nouvelles remarques, j'attends celle des autres.

EDIT : En supprimant les comptoirs entrée + bar on descend à 1350€, c'est pas du tout négligeable.

**Comment by AlexFourgs** [comment]
Clairement !

Du coup faut voir pour les arbres mais faut rester dans une logique. Genre moi j'aime bien l'idée que pour les endroits principaux (régie DJ, Bar, entrée) on est genre des arbres comme ça, c'est drôle, mais partout je sais pas. J'aurais plutôt dis les colonnes LED partout, tout en sachant qu'il va falloir faire gaffe aux éventuelles dégradations...

On valide le budget comm' du coup, merci de rajouter le devis dans la partie code ;)

**Comment by arya-coding** [comment]
Oui c'est une possibilité intéressant d'en installer que aux endroits centraux (bar, entrée, dj).
Pour les colonnes LED, c'est une bonne idée, je penserais à ce que faisais la wanderlust, 

![wanderlust_copyright i heart paris kim laidlaw adrey13](https://cloud.githubusercontent.com/assets/9800251/18933036/220f8e4a-85d3-11e6-95e2-66c231e2fdfb.jpg)

OU encore : http://static1.villaschweppes.com/articles/3/21/44/3/@/140343-wanderlust-article_top-3.jpg
Donc il faut l'imaginer en pénombre et les néons ont des couleurs différentes, et ca rendait vraiment pas mal ! On pourrait faire quelquechose de similaire au plafond en les collant simplement, mais l'alimentation reste le problème... à moins qu'on prenne à pile/batterie.

**Comment by AlexFourgs** [comment]
Y'a écrit sans fil les colonnes que t'a mis dans ton devis

**Comment by arya-coding** [comment]
Mais on va pas scotcher des colonne lumineuse au plafond Mdrr, elles font jusqu'à 24Kg. Tu veux tuer des gens toi.

Je pensais davantage à ça. Léger, différents mode à batterie. (De plus, on peux facilement les stocker, ranger et même les utiliser pour le local, meuble DJ par exemple).

![qsdsqcapture](https://cloud.githubusercontent.com/assets/9800251/18933304/732c06e0-85d4-11e6-89db-23740eddf899.PNG)
https://fr.aliexpress.com/item/High-Brightness-Battery-LED-Strip-Light-RGB-Warm-Cool-White-SMD-5050-Waterproof-IP65-String-4/32693611596.html?spm=2114.06010108.3.9.CwU0E9&ws_ab_test=searchweb201556_0,searchweb201602_5_10057_10056_10065_10068_10055_10054_10069_10059_10058_418_10073_10017_10072_10070_10060_10061_10052_10062_10053_10050_10051,searchweb201603_3&btsid=bae8e437-5809-4d45-85b8-48dee34b5a32

EDIT ; Ou bien, des "fils lumineurs"
https://fr.aliexpress.com/item/1m-3m-5M-3V-Flexible-Neon-Light-Glow-EL-Wire-Rope-tape-Cable-Strip-LED-Neon/32437662861.html?spm=2114.06010108.3.57.CwU0E9&ws_ab_test=searchweb201556_0,searchweb201602_5_10057_10056_10065_10068_10055_10054_10069_10059_10058_418_10073_10017_10072_10070_10060_10061_10052_10062_10053_10050_10051,searchweb201603_3&btsid=bae8e437-5809-4d45-85b8-48dee34b5a32
![8779capture](https://cloud.githubusercontent.com/assets/9800251/18933385/c9bba196-85d4-11e6-9353-efe0b7e1c28e.PNG)

**Comment by AlexFourgs** [comment]
Mec, la sécu je vais lui dire LED alliexpress elle va me dire on annule tout !

**Comment by arya-coding** [comment]
C'était juste pour présenter le produit, on pourra le prendre chez un autre fournisseur

**Comment by AlexFourgs** [comment]
Point important qu'on a oublié d'évoquer, le jour de l'événement une commission de la mairie va venir sur le lieu de l'événement afin de s'assurer qu'on soit en règle et qu'on a penser à toute la sécurité & inc, donc on va éviter de prendre des risques avec des leds aux plafonds.

Comme je l'ai dis, de simple draps qui "pendent" un peu suffiront à changer un peu l'aspect du hall et permettront de faire mieux ressortir les lumières provenant de la scène.

Après ça reste mon point de vue.

**Comment by arya-coding** [comment]
Ba le risque ne vient pas des LEDS en elle même, mais des batteries qui alimenterons chacune des barres :/

EDIT : Plus simple, plus safe, moins cher et même fournisseur...

![qsdsqcaptursse](https://cloud.githubusercontent.com/assets/9800251/18933586/d2f22004-85d5-11e6-8f47-bbe8ebbc77f3.PNG)

**Comment by AlexFourgs** [comment]
Après relecture, surtout pour la partie table scolaire, la vie associative met à disposition chaises et tables pliantes qui sont celle qui était sur le parvis à la journée festive, pour moi c'est très bien, juste on ajoute une nappe propre blanche pour faire plus jolie et le tour est joué

**Comment by AlexFourgs** [comment]
Devis de Barnum (prestataire bières) :

Pour faire suite à notre entretien je vous prie de trouver ci-dessous notre proposition :
- Meuble Pression FESTIVAL 2 colonnes - Location / Installation : 145€ ht /174€ ttc [Offert à partir de 10 fûts consommés]
- Forfait Gaz CO2 : 30,00 € ht / 36,00 € ttc

Quelques exemples de bières disponibles (Seuls les fûts consommés ou entamés sont facturés) :
- Fût KRONENBOURG 30 Litres : 78,80 € ht / 94,56 € ttc
- Fût STELLA Blonde 30 Litres : 79,90 € ht / 95,88 € ttc
- Fût GROLSCH Blonde 30 Litres : 96.83 € ht / 116.19 € ttc
- Fût GALLIA Bière Blonde de Paris 30 Litres : 105€ ht / 126€ ttc
- Fût HEINEKEN 30 Litres : 112.50 € ht / 135 € ttc
- Fût 1664 Premium 30 Litres : 112.5 € ht / 135 € ttc
- Fût LEFFE Abbaye 30 Litres : 129,80 € ht / 155.76 € ttc
- Fût AFFLIGEM Abbaye 30 Litres : 129,80 € ht / 155.76 € ttc
- GOBELETS PP Lisse 25 cl (x 80) : 3.30€ ht / 3.96€ ttc
- COMPTOIR de Service Inox pliable KLAPPOBAR L 150 cm - Location/Installation : Offert

N’hésitez pas à nous interroger pour les autres boissons de votre événement (eaux, jus de fruits, softs, vins, champagne,…) : nous vous ferons la proposition la plus attractive…

Possibilité de livraison et reprise à Paris et petite couronne: Forfait de 62,00 € ht / 74.4 € ttc (prix pour livraison et reprise en semaine)

**Comment by Uinelj** [comment]
## Dimensionnement

Il nous faut maintenant dimensionner tout ça.
@Najentun Demande peut-être à ton contact niveau Bar des Banques si il a des tips.

Il nous faudrait idéalement : 
- Le nombre d'heures d'ouverture du bar
- La proportion de buveurs
- Combien de litres va consommer en moyenne chaque buveur
- ?

Avec ces informations on va pouvoir calculer la quantité de bière consommée par personne, et avoir une estimation grossière de nos besoins.
On commandera un peu plus que prévu, histoire d'être large.

On **doit** également calculer comment on dimensionne nos softs.

# Balance

On calcule ensuite le coût de notre commande Barnum, et on voit combien de bénéfices on peut en tirer. Ces bénéfices théoriques pourront être mentionnés en subvention, et rembourser, par exemple, le financement lié à la décoration.

**Comment by AlexFourgs** [comment]
## Bière(s) :
- D'après Barnum, sur un événement de cette envergure il n'est pas forcément nécessaire de proposer deux bières différentes qui ajoute une charge de gestion en plus qui n'est pas forcément nécessaire et plutôt partir sur un "classique" (Heineken, 1664, ...).
- Si on voit trop gros pour la bière c'est pas un problème, Barnum les récupères et nous rend 100% du prix des fûts.
- 4 colonnes me semble bien, vu où sera situé le bar, il est préférable qu'on gère aisément l'affluence.
- 20 fûts (600L) me semble très bien (1.7L de bière par personnes, sachant que certains en boiront plus, et d'autres moins, mais surtout tenir compte que l'événement dure 6h ! Perso en 1h30/2h je bois 1L de bière aisément), et puis si les 20 fûts sont consommés, ça rembourse les 4 colonnes de bières.

## Soft(s) :
- Quantité(s) la grande question !
- Quelles boissons ?
- Solution(s) stockage au frais à demander (frigo, bac à glaçons, ...)

## Divers :
- Gobelet(s) de 50cl (1200 ?)
- Comptoir offert !
- Demander pour la livraison à Cergy-Pontoise, prix/dates, influence sur la location.

**Comment by AlexFourgs** [comment]
Très bonne nouvelle, Gilles (prestataire sono, régie DJ) s'occupe aussi des lumières !

**Comment by AlexFourgs** [comment]
## Les comptoirs fournis GRATUITEMENT par Barnum

![Dimensions comptoir](https://raw.githubusercontent.com/bdeecho/Chaudiere/master/Images/KlappoBar%20Barnum%20Dimensions.jpg)
![comptoir](https://raw.githubusercontent.com/bdeecho/Chaudiere/master/Images/Configuration%20Comptoirs%20KLAPPOBAR.jpg)

## Précisions sur les tireuses à bières

[Barnum-meuble pression Festival.pdf](https://github.com/bdeecho/Chaudiere/files/501094/Barnum-meuble.pression.Festival.pdf)

**Comment by AlexFourgs** [comment]
Ne pas oublier de demander la caution pour chaque location :
- Décisions accoustiques
- Barnum
- Kiloutou
- Solutions événements

**Comment by AlexFourgs** [comment]
## Devis solutions-événements (Vestaire + Décoration)
- Pas de nappes
- Pas de bananiers (ajouter deux palmiers pour remplacer ?)

[DEVIS-D7204-BDE__Echo-FOURGS-Alexandre.pdf](https://github.com/bdeecho/Chaudiere/files/502330/DEVIS-D7204-BDE__Echo-FOURGS-Alexandre.pdf)

**Comment by AlexFourgs** [comment]
En ce qui concerne les softs, une bouteille pour deux personnes (75cl par personnes) ça vous semble bien ?

**Comment by Uinelj** [comment]
@nowanda92 a proposé une bouteille par personne si je me souviens bien. On peut probalement partir là dessus ?

**Comment by AlexFourgs** [comment]
Non il a dit 1 bouteille de 2L pour deux personnes soit 1L par personne.

**Comment by Uinelj** [comment]
Ok, ça me semble tout bon alors ! 

Il faut recontacter Barnum pour les informer qu'on sera moins que prévu.

**Comment by Uinelj** [comment]
Le nouveau devis solutions-événements a été demandé et devrait arriver d'ici 24/48h.

**Comment by AlexFourgs** [comment]
[MAJ] Ajout des devis de Barnum et Solutions-événements.

Il manque :
- Gardiennage
- Kiloutou (en cours, je dois envoyer un mail)
- Sono + Light
- Prévention

**Comment by AlexFourgs** [comment]
Il nous manque donc :
- Gardiennage (je vais voir la vie asso ce matin pour savoir si il y a des nouvelles) 
- Sono (Relancer Gilles rapidement car on doit faire passer le devis à Pascal avant qu'il nous le renvoie) 
- Prévention (Contacter rapidement croix rouge) 
- SACEM

**Comment by AlexFourgs** [comment]
**GROSSE MAJ**

**Comment by AlexFourgs** [comment]
**MAJ** Demande de sub' avec la prise en compte du pire des cas et du meilleur des cas.

Il manque toujours les t-shirts (je les relance), et croix rouge (@Uinelj est sur le coup).

Dans la demande de subvention on a fixer le gardiennage et sécurité à 3300€ sachant que ça a était dit lors d'une réunion et le cachet artiste à 1500€ (d'après la dernière demande de sub il me semble).

**Comment by AlexFourgs** [comment]
Les deux demandes sont prêtes :
Hall Saint Martin 375 personnes : https://github.com/bdeecho/Chaudiere/blob/master/Cadence-1/demande_subvention_fsdiefave%20cadence%201%20340%20personnes%20hall.odt
RU Saint Martin 465 personnes : https://github.com/bdeecho/Chaudiere/blob/master/Cadence-1/demande_subvention_fsdiefave%20cadence%201%20430%20personnes%20RU.odt
