### ISSUE TITLE
Amener un food truck ?

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#28]
On pourrait proposer, au fumoir, un food truck permettant aux gens de manger un bout.

Voir avec le food truck qui est souvent sur le parvis des Chênes.

**Comment by AlexFourgs** [comment]
Perso je trouve ça super cool, ça permet d'ajouter le facteur bouffe à l'événement et si c'est un food truck on a rien à gérer.

Les problèmes qui se posent en revanche sont :
- Trouver un emplacement, et y'en a pas 36, pour moi le mieux ce sera au niveau de l'entrée principale, mais ça pose un autre problème qui est celui de la sécurité, pour éviter les intrusions d'inconnus dans l'événement on est obliger de baliser partout et surtout au niveau de l'entrée principal ou y'a le fumoir, si on ajoute le foot-truck on va devoir agrandir la zone, ce qui implique des problèmes liés à la sécurité (évacuation et tout le tralala).

**Comment by AlexFourgs** [comment]
Le food truck de la fac est chaud pour un rdv un midi vers 14h

**Comment by AlexFourgs** [comment]
Après prise de contact avec le foodtruck au chênes, on doit leur confirmer la date le plus tôt possible, et surtout faire la demande administrative (fac ou mairie) pour le foodtruck devant St Martin.

**Comment by AlexFourgs** [comment]
Le trottoir appartient à l'Université, je pense qu'une prise de contact à ce sujet auprès de la vie associative nous permettrait d'obtenir les autorisations nécessaires.

**Comment by Uinelj** [comment]
Yep, et il faudra bien entendu relancer le Camion du Vexin.

**Comment by AlexFourgs** [comment]
On attend que l’événement soit confirmé et que la vie associative nous aide pour l'autorisation sachant qu'il faudra adapter la zone de balisage.

**Comment by AlexFourgs** [comment]
Ne pas oublier de négocier des repas gratos pour staff et artistes.

**Comment by AlexFourgs** [comment]
Problème réglé, le CROUS gère la nourriture avec des burgers + frites pour 4€.
