### ISSUE TITLE
Organiser et prioriser nos canaux de communication.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#29]
Il nous faut faire une liste des gens à qui balancer l'information et la com, et prioriser cette liste.

L'idée, c'est de savoir toucher les **bons** publics. Le challenge, c'est qu'on a un grand nombre d'étudiants qui sortent se murger à des Afterworks de BDE et qui pourraient confondre notre événement avec un truc du genre. Il faut donc **absolument** gérer notre communication, et permettre aux amateurs de musique de prendre leur place, afin d'éviter d'avoir 70% de nos places prises par des gens qui s'attendent à voir du Guetta et de la Vodka.
## Liste de "canaux" désorganisée
- Les adhérents intéressés
- Les BDE Partenaires (Héro, AFAC) et leurs adhérents
- CampUcp
- Affiches dans la fac
- Squaresound / LaRuche
- CDH/CDP

**Comment by Beat-nique** [comment]
CDP => cf poste hebdomadaire dédié à la promo des événements de la semaine

De plus, je pense qu'il faut réfléchir différemment pour ce qui est de la comm et son ciblage. 

LE PLUS IMPORTANT : communiquer sur l'événement LE PLUS TÔT POSSIBLE (1 mois à l'avance c'est bien, moins de 2 semaines ça devient très risqué)

Autre objectif : atteindre le plus de personnes possibles ! L'écrémage, pour ce qui est de la population de la soirée, se fera via des publications sur la page de l'événement de type : post de morceaux ou de sets des artistes, bio et description des artistes, articles sur l'histoire de la House, etc.

Une petite astuce pour garantir que les gens qui veulent juste se la coller ne se ruent pas sur les places avant de se rendre compte que ce n'est pas pour eux => lancer l'événement 5 jours à 1 semaine avant la vente des places. Comme ça, ça vous laissera le temps de publier sur l'événement pour bien communiquer sur l'esprit de la soirée.

Après tout cela, n'est que ma vision des choses bien entendu.
