### ISSUE TITLE
Thématiques des boiler room.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#3]
Comme décidé précédemment on va se baser sur 3 évènements de la sorte pour l'année. 
Je pense qu'il serait intéressant d'aller du plus accessible au moins accessible. Ainsi : 
1. Boiler House/DeepHouse, qui peut fédérer des gens qui sont pas forcément house-addicts, mais aussi des gens curieux qui aiment l'électro en général
2. Boiler Tech-House, un peu moins accessible mais il y a un public, auquel on ajoute les convaincus de la Boiler House/DeepHouse
3. Boiler Techno, le truc ghetto dans le parking ou on se tue les oreilles.

Des remarques/suggestions ?

**Comment by AlexFourgs** [comment]
Parfait, l'idée des boilers crescendo permettra d'inviter petit à petit le public qui n'est pas forcément electro-addict à découvrir le "véritable" monde de la culture musique électronique.

La Tech-House reste assez festif malgré tout suivant les artistes (y'a du ghetto et du moins ghetto mais ça faudra voir au niveau de la prog').

Moi perso ça me convient parfaitement.

Pour le grand public on peut faire un événement EDM lors du festival, mais ça on en rediscutera lors des réunions avec la fédé et toi et moi ;)

Perso je valide ces 3 boilers, reste à trouver un nom pour ces événements ainsi que les dates (je vais contacter les principaux BDE organisateurs de soirées étudiantes pour obtenir leurs calendriers si ils les ont fait).

**Comment by AlexFourgs** [comment]
Tu peux close l'issue ;)
