### ISSUE TITLE
Gaufrerie / Cadence gourmande

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#30]
# Gaufrerie / Cadence gourmande
## Présentation du projet

Le but des cadences gourmandes est de reprendre le principe des gaufreries organisées par l'ancien bureau en y ajoutant le côté musique avec un set DJ (étudiants de l'université ?).
Un point important à souligné, ça fonctionnerait sous forme de "tournée" (comme les concerts) sur l'ensemble des différents gros sites de l'UCP (Chênes, St Martin, Neuville).
### Cadence gourmande # 1
- Date : Jeudi 3 Novembre 2016
- Lieu : À déterminer
- Staff :
  - Alexandre FOURGS
  - Julien ABADJI
### Cadence gourmande # 2
- Date : Jeudi 10 Novembre 2016
- Lieu : À déterminer
- Staff :
  - Alexandre FOURGS
  - Julien ABADJI
### Cadence gourmande # 3
- Date : Jeudi 17 Novembre 2016
- Lieu : À déterminer
- Staff :
  - Alexandre FOURGS
  - Julien ABADJI

**Comment by Uinelj** [comment]
C'est une super idée.

Cela demande une petite logistique, c'est à dire : 

1/ Faire trois demandes de manifestation
2/ Trouver du staff qui pourrait s'occuper de la vente de crêpe (qu'on soit au moins 3 en tout)
3/ Trouver des dates : A priori on n'aurait pas cours pendant 3 semaines en Novembre, il faudrait se caler un midi ou une après midi ? 
4/ Trouver QUOI vendre ? Si on vend des crêpes à midi c'est meh non ?

**Comment by AlexFourgs** [comment]
1/ Pour la demande de manif, théoriquement il faut qu'on les fassent une semaine avant, mais le facteur set DJ peut faire varier le temps, même si dans un sens c'est juste un fond sonore plus qu'un set DJ.

2/ Voir avec Alexis qui était chaud pour, après on peut voir au niveau de notre classe si des gens sont chaud ( @Eresia, @akkes, etc...)

3/ Autant viser le même jour de la semaine d'après moi. On pourrait appeler ça "le mois des cadences gourmandes" et essayer de le reproduire un deuxième mois au second semestre ? 

4/ Des gaufres comme on a acheté 3 machines, après tout dépend du "format", si tu fais un 10h-14h, tu vise la pause de 10h, et celle de 12h !

**Comment by Eresia** [comment]
Je suis partant

**Comment by clairengn** [comment]
Il est aussi possible de faire des gaufres "salés" pour le midi, sinon l'appareil a gaufre comprend aussi des plaques pour croque monsieur normalement. Donc pourquoi pas faire un menu Croque, gaufre en dessert et boisson ?

**Comment by AlexFourgs** [comment]
@clairengn très bonne idée !

à discuter rapidement afin de faire les "devis" et les recettes prévisionnelles + les demandes de manifestations !

**Comment by clairengn** [comment]
D'accord je peux m'occuper du devis et des recettes ! Il faut juste que je sache pour combien de personnes environ on prévoit de vendre, et où l'on va se fournir pour les ingrédients.

**Comment by AlexFourgs** [comment]
Merci claire ! Mais une toute petite réunion (ou alors on en parle rapidement au RU avant) serait peut-être intéressante afin d'avoir les avis et idées de tous, et surtout qui serait chaud niveau staff pour organiser ça ?

**Comment by AlexFourgs** [comment]
Ce serait cool de fixer les dates, je vais lancer un votes sur le groupe Facebook. Merci de répondre RAPIDEMENT.

**Comment by AlexFourgs** [comment]
MAJ Informations.

Les dates sont fixées, il ne reste plus qu'à fixer les lieux des manifestations.

En attendant, quelqu'un pourrait faire un devis ? @clairengn toi qui était motivé, si tu veux tu peux t'en occuper :) 
Par contre je sais pas du tout combien de gaufres on peut s'attendre à vendre durant les trois événements sachant que le lieu va avoir un fort impact (par exemple on va vendre + de gaufres à la MDE des chênes qu'à St Martin). Le format horaire va lui aussi avoir un impact sur les ventes.

**Comment by clairengn** [comment]
[Devis Gaufres.pdf](https://github.com/bdeecho/Chaudiere/files/549145/Devis.Gaufres.pdf)
[Recette Gaufre.pdf](https://github.com/bdeecho/Chaudiere/files/549146/Recette.Gaufre.pdf)

Voila un premier devis et la recette éventuellement prévue pour les gaufres. J'ai prévu le devis pour 160 gaufres environ, il nous suffira de multiplier les doses si l'on prévoit plus.

**Comment by clairengn** [comment]
Est ce que je rajoute à cela le nutella, confiture et autre avec? (boissons...)

**Comment by AlexFourgs** [comment]
Très beau travail ! 
Je veux bien oui, apparemment la confiture ça marche pas des masses, par contre nutella, chantilly et sucre en poudre ça marche très bien. 
Une étude aussi sur ce que ça pourrait nous rapporter suivant le prix à laquelle on vend la gauffre serait hyper intéressante. 

Merci pour ton travail Claire :) 

Il faut que je fasse les demandes de manifestations mais je ne sais pas ou ce sera encore. Je pense aux Chênes pour la première semaine.

**Comment by akkes** [comment]
Je peux faire mon hipster et demander du Niccolata aussi? http://rigonidiasiago.fr/index.php/nos-produits/nocciolata.html 😛

**Comment by Uinelj** [comment]
Ca dépend, ça se trouve partout ?

**Comment by clairengn** [comment]
Moi aussi je vote pour le niccolata ! Y'en a des tonnes chez moi si vous voulez :p (sinon à leclerc il y en a c'est sure)

**Comment by clairengn** [comment]
-Sucre glace Daddy : 1,62€ (prévoir 2 ou 3 pot, ça se conserve donc autant en prendre plus)
-nutella : 2,97€ (4 pots au minimum), il vaut mieux prendre la vraie marque car les assos qui vendent des crêpes avec le nutella marque pouce c'est degeulasse et les étudiants achètent moins
-crème chantilly bridélice : 2,05€ (5?) 

Je pense qu'un prix de vente de : 
-80cts gaufre sucre
-1€ gaufre au nutella 
supplément chantilly : 20cts

Imaginons que l'on vende la moitié des gaufres  au sucre donc : 0,8x110=88€
La moitié au nutella : 1x110=110€ 
Et 1/4 des gaufres avec supplément chantilly : 0,2*55=11€ 

On serait donc sur un benef d'environ 209€ si tout se passe comme prévu, avec un coût d'un peu plus de 15€ pour les gaufres + les coûts pour les garnitures mais ça dépendra des quantités que vous prévoyez.
