### ISSUE TITLE
déCadence/Apéro Openmix #1

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#31]
Il faut commencer à faire des apéros Openmix.
## Nom

 Si on veut rester cohérent, il nous faut un nom contenant Cadence, mais si apéro openmix ça vous va il n'y a pas de soucis :)
## Date

Seconde moitié d'Octobre ? 
On aura la subvention Cadence#1 passée, et donc probablement une charge de travail réduite. 
Réfléchissons à la couleur que l'on veut donner à ce premier événement.
## Genre

A mon avis, une musique relativement "grand public", de la House toute gentille, uplifting, qui se mélangerait pourquoi pas avec des trucs un peu chill ?

**Comment by AlexFourgs** [comment]
## Nom

"Apéro déCadence" je trouve ça cool, ça mixe les deux.

## Date
- Semaine du 17 Octobre :
  - Lundi trop tôt dans le semaine amha
  - Mardi un peu trop tôt aussi
  - Mercredi c'est mort on quitte à 19h
  - Jeudi bloqué par Coven
  - Vendredi c'est cool mais c'est risqué. Cool parce que fin de semaine et début de week-end, de quoi bien commencer le week-end. Risqué parce que les gens ont peut-être déjà prévu quelque chose le même soir, ou le samedi et préfère peut-être se reposer etc...

## Lieu

Barrabouda on a pas le choix.
**Voir avec la vie asso s'il est nécessaire de faire une déclaration de manif.**

## Genre

J'aurais bien aimé caler Guillaume avec son style un peu plus mainstream en ouverture, et petit à petit partir sur de la House plus classique avec @uj ou moi ou tous les deux ensemble même si je trouve ça dommage de se séparer des éventuelles étudiants qui viennent pour nous connaitre nous et l'association. On prend un risque si on mix tous les deux.

**Comment by Uinelj** [comment]
Au pire on fait 3 sets : 
- Guillaume
- uj
- Trême

Comme ça un membre du bureau toujours open :)

**Comment by Beat-nique** [comment]
Sinon petite idée de nom d'événement : petit jeu de mots de merde qui mixe Cadence et l'idée d'apéro, vous appelez ça : L'en-cas Dance. Et en image pour l'événement vous mettez genre une photo de saucissons avec du fromage et de la bière pour bien associer ça à l'apéro.

**Comment by Uinelj** [comment]
C'est vrai que ça mixe nos deux idées, c'est une proposition à voir !

Je pense que du moment où on se différencie des afterworks classiques on est gagnants.

**Comment by Beat-nique** [comment]
Je pense que pour l'instant il y a même pas besoin de chercher à se différencier de l'afterwork classique, rien que le fait d'être à Cergy c'est une différence. Je pense qu'il y ait d'autres afterworks à Cergy. L'enjeu serait de se vendre comme LA référence en tant qu'afterwork à Cergy. Que les gens pensent direct à l'événement quand il pense à un afterwork dans les environs.

**Comment by Uinelj** [comment]
Le truc c'est que justement, à l'UCP t'as plein d'assos qui font des afterwork. Leur concept c'est surtout un prétexte à la tise cheap, et la vie associative, qui est derrière nous, aime pas cette image.
Pour te dire, il y a même une asso qui fait des afterwork tous les jeudi soir au Barrabouda. Donc c'est assez saturé. Mais en soi, on vise une catégorie qui n'est pas nécessairement la même donc..

Au final, avoir un non différent c'est surtout pour se différencier par rapport à la vie associative qui soutient nos projets.

**Comment by AlexFourgs** [comment]
En ce qui concerne la date :
- Vendredi 21 compliqué à cause de la demande de manif.
- Vendredi 28 impossible car vacance + WEI REMED
- Il reste donc le vendredi 4 novembre (on sera en période de "vacances")

**Envoyer la demande de manifestation**

**Comment by AlexFourgs** [comment]
Contacter Budda.

**Comment by Uinelj** [comment]
Je m'en occupe aujourd'hui.

**Comment by Uinelj** [comment]
La date est fixée, ça sera le 4 Novembre, 18h-21h.

**Lineup** : 
- Trême (1h DJ Set)
- uj (1h DJ Set)
- Gamys (1h DJ Set)

**TODO** : 
- Faire une bannière FB avec : Logo UCP, Logo Barrabouda, Logo Echo, Lineup, Date, Lieu. Bannière : 784*295.

**Comment by Uinelj** [comment]
Event lancé : https://www.facebook.com/events/597796273762355/

**Comment by AlexFourgs** [comment]
On close.
