### ISSUE TITLE
Lineup Cadence #2

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#33]
## Style

On s'orienterait potentiellement vers des genres de house un peu atypiques, type _dub_, _micro_, ce genre de choses. Dans le style de Mr.G, Brawther, et potentiellement évoluer au fil de la soirée sur de la micro.
## Artistes contacts

**Artiste contact = Artiste avec qui on peut avoir un contact privilégié.**
- [Aymeric Duvi](https://www.facebook.com/aymericdude)
- [Antoine Sy](https://www.facebook.com/AntoineSyBinarySound)
- ([LeLoup]())
- ([Varhat](https://www.facebook.com/varhatyoyaku/?ref=br_rs))
- ([Zendid](https://www.facebook.com/ZendidOfficial/))
- [Malouane](https://www.facebook.com/malouanehouse)
- [Le Goff](https://www.facebook.com/vlgneyvia)
- [ALVA](https://www.facebook.com/alvamusics)
- [Al-Jinn](https://www.facebook.com/Al-Jinn-1529355137346957/)
- [Rheostat : Bassam](https://www.facebook.com/rheostatbassam/?fref=ts)

**Comment by Beat-nique** [comment]
Rajoute : 
https://www.facebook.com/malouanehouse/?fref=ts
https://www.facebook.com/vlgneyvia/?fref=ts
https://www.facebook.com/alvamusics/?fref=ts
https://www.facebook.com/Al-Jinn-1529355137346957/?fref=ts
https://www.facebook.com/victor.arnau?fref=ts (Chineurs de Paname)
https://www.facebook.com/rheostatbassam/?fref=ts (pote d'Antoine Sy)

et mets entre parenthèses Zendid, Varhat et Le Loup, sachant que ça c'est des contacts d'Antoine. Ce sera donc plus long pour rentrer en contact et je pense que de toute façon on ne pourra les booker que si on booke déjà Antoine.
