### ISSUE TITLE
Salle du campus Hirsch

### ISSUE THREAD

**Issue by arya-coding** [bdeecho/Chaudiere#34]
Bonjour,

De passage à Hirsch, je vous présente dans une petite vidéo le campus et la salle qui serais intéressante pour une cadence.

https://www.youtube.com/watch?v=ey-1gPhqxIQ&feature=em-upload_owner

Bon visionnage,

Tenez moi au courant

**Comment by AlexFourgs** [comment]
Merci Arya !

Par contre j'ai l'impression que la salle n'est pas assez grande, mais ça peut être une idée pour un petit événement type "mini Cadence".

**Comment by Uinelj** [comment]
Yep, ça a l'air clairement sous dimensionné.

**Comment by AlexFourgs** [comment]
Éventuellement si on fais un apéro dans les locaux de la fac ?
