### ISSUE TITLE
Contacter l'assurance

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#35]
Appeler l'assurance pour revoir le contrat (par rapport aux nombres de personnes durant nos événements) + pour voir si on peut être assurer au niveau matériel le temps de nos événements (assurance matériel pour palier aux problèmes de cautions très élevés).

**Comment by AlexFourgs** [comment]
Si les demandes auprès de la mairie le 25 octobre après-midi ne prennent pas trop de temps (cf #23) on pourra passer à l'assurance après la mairie ?

**Comment by Uinelj** [comment]
Autant faire d'une pierre deux coups !

**Comment by AlexFourgs** [comment]
L'assurance me recontacte vendredi.

**Comment by AlexFourgs** [comment]
Mail de Valérie Gandy :

Bonjour,
 
Vous pouvez m’appeler au 01.30.31.89.42 pour fixer un RV.
 
Nos bureau sont ouverts de 9h30 à 12h et de 14h à 17h30.
 
Cdt


**À contacter rapidement**
