### ISSUE TITLE
Demander des barrières et autorisation de stationnement à la mairie de Pontoise

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#36]

**Comment by AlexFourgs** [comment]
cf #23

**Comment by AlexFourgs** [comment]
Contacter la voirie pour la demande de barrières et l'autorisation de stationnement sur l'avenue François Mitterand. 

Coordonnées :
Mairie de Pontoise, centre technique municipale 
6 rue Ampère 95300 Pontoise
0134415420 ou 0134415424

**Comment by Uinelj** [comment]
Voirie contactée, compte rendu des échanges téléphoniques : 
- Ils peuvent supply quelques barrières mais honnêtement je pense qu'on peut faire sans.
- Pour le stationnement, il faut le stipuler lors de la demande d'arrêté. Si j'ai bien compris c'est l'Université qui s'occupe de déclarer l'événement à la préfécture, donc on a "juste" à demander à l'Université de le faire.

Le mec m'a dit de pas trop tarder, mais il était cool.

**Comment by Eresia** [comment]
Intéressé pour Versity aussi !

**Comment by AlexFourgs** [comment]
L'Université a quelques barrières de chantiers, mais faut voir si ils peuvent les transporter jusque St Martin.

**Comment by AlexFourgs** [comment]
Je close ici, l'affaire est réglée.
