### ISSUE TITLE
Faire une demande auprès de la SACEM

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#37]
Afin d'avoir le droit de diffuser de la musique durant nos événements, il est nécessaire de faire une demande auprès de la SACEM.
- Si on obtient l'autorisation 15 jours minimum avant l'événement en question, on obtient une réduction de 20%.
### Concert / Spectacle ?

https://clients.sacem.fr/autorisations/concert-ou-spectacle

Étant donné qu'on est dans la catégorie "événement qui coûte plus de 3000€ et/ou billet d'entrée à plus de 20€", on va devoir reverser 100% des recettes perçues sur la vente des billets + 50% des recettes annexes... Autrement dit on va rien gagner sur l'event...
### Établissement d'enseignement ?

https://clients.sacem.fr/autorisations/etablissement-d-enseignement
### Pour le stream ?

https://clients.sacem.fr/autorisations/ecoute-de-musique-a-l-unite

**Comment by Uinelj** [comment]
On peut voir avec Pascal / Gilles aussi si ils n'ont pas des tuyaux.

**Comment by Eresia** [comment]
Y a beaucoup de bail autour de la SACEM, faut se renseigner

**Comment by AlexFourgs** [comment]
J'ai envoyé un mail à la vie culturelle à ce sujet.

**Comment by akkes** [comment]
À mon avis faut aller dans "Discothèque ou bar dansant": https://clients.sacem.fr/autorisations/discotheque-ou-bar-dansant. Les conditions exactes sont dans le détail des tarifs

**Comment by AlexFourgs** [comment]
Merci Louis !

À voir aussi, comme l'a souligné @Uinelj, avec la vie culturelle ou décisions-acoustiques si ils ont pas des bails.

**Comment by Uinelj** [comment]
On tombe dans ce cas de Discothèque ?

**Comment by Eresia** [comment]
Plutôt de bar dansant je crois

**Comment by AlexFourgs** [comment]
Je pense passer à la vie asso et culturel ce matin pour avoir de plus amples informations.

**Comment by AlexFourgs** [comment]
La vie culturelle peut pas faire grand chose apparemment, mais les personnes présentes à la réunion technique sont en vacances donc informations à confirmer. 

Gilles a été solliciter aussi, en attente d'une réponse de sa part. 

Demander à Pascal aussi.

**Comment by Beat-nique** [comment]
De mon expérience sur ce genre d'événement théoriquement il faut payer la sacem mais personne ne le fait jamais et je n'ai jamais entendu personne avoir de problème à cause de ça

**Comment by AlexFourgs** [comment]
@Beat-nique j'aimerai bien ne pas le déclarer, mais le problème c'est qu'on est dépendant de l'Université donc on peut pas trop prendre de risque à ce niveau...

**Comment by Beat-nique** [comment]
Bah nous on organisait tout dans le cadre de notre école et on a jamais eu de pb. Mais si tu veux je peux sonder les présidents des assos musicales de mon école pour voir comment eux ils géraient le truc
