### ISSUE TITLE
Faire les affiches et flyers.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#38]
Ce serait cool d'avoir une version alpha des affiches, ça va arriver vite et il faut que la communication soit prête à être lancé dès qu'on a le feu vert final.

@aryus96 je te laisse faire une première version, prend n'importe quelle police on pourra la changer au pire.
@Uinelj je te laisse donner tes idées sur l'idée qui doit ressortir de l'affiche.

**Comment by AlexFourgs** [comment]
La police : http://www.losttype.com/font/?name=venera

**Comment by arya-coding** [comment]
Okok je suis assez pris en ce moment, mais j'essaierais de faire quelque chose.

**Comment by AlexFourgs** [comment]
Merci mec !

**Comment by AlexFourgs** [comment]
Au final t'a le temps :)

**Comment by AlexFourgs** [comment]
![13509131_1831095950454295_3170797438125875041_n](https://cloud.githubusercontent.com/assets/15659639/20314515/c57e580c-ab5a-11e6-8b51-4fe0de02d755.png)

Un truc dans le genre avec St Martin en fond serait vachement sympa aussi, je sais pas ce que vous en pensez.

**Comment by Uinelj** [comment]
DE FOU

**Comment by AlexFourgs** [comment]
On est d'accord qu'on part sur un truc dans le genre ? (affiche chineurs de panam)

Si c'est le cas il faut mettre les photos de Saint Martin ici pour @aryus96 et je vais envoyer un mail à la vie associative si on est libre de les utiliser pour une affiche ou éventuellement demander à Roxanne si elle peut faire quelques photo ?

Je pense qu'il serait intéressant de faire une petite liste des éléments à mettre sur l'affiche pour aider Arya dans son travail aussi.

**Comment by arya-coding** [comment]
Premier draft
Rien n'est réglé au millimètre prés, on s'intéresse ici au layout général

![draft2 copie](https://cloud.githubusercontent.com/assets/9800251/21388532/f71051f2-c77c-11e6-9f3a-474e71d989e6.jpg)

![draft2 copie](https://cloud.githubusercontent.com/assets/9800251/21388833/767d2018-c77e-11e6-83fa-71c4f63dca21.jpg)

![draft2 copie](https://cloud.githubusercontent.com/assets/9800251/21390718/9946eebc-c788-11e6-8015-89e95345a909.jpg)

**Comment by AlexFourgs** [comment]
Franchement vraiment bien, j'adore ce côté "brut" avec le fond bleu un peu ghetto et la coupure avec la fac. Tu penses pouvoir un petit peu "ghettoïser" le bâtiment de la fac, c'est peut-être un peu trop net comme coupure ?

Après sur le contenu textuelle je pense qu'il serait cool de mettre "Cadence #1" pour bien faire comprendre que c'est la première et pas la dernière. 
Pas la peine de mettre Techno House, je pense qu'on axera ce point sur la communication à travers les réseaux sociaux et notre site.
Date / Lieu juste en dessous de "Cadence #1" ? 
La line up à la place de la date et lieux (pour l'instant met juste Artiste 1, artiste 2, etc...)


Merci Arya pour ton superbe boulot et de nous accorder de ton temps ;)


Edit : J'ajoute aussi le fait que cette charte graphique se démarque des autres BDE, on a ici une affiche plus conviviale et qui fait moins appel à la soirée étudiante beuverie & inc et d'après moi c'est nickel sur le message de fond ;)

**Comment by Eresia** [comment]
J'adore vraiment

**Comment by arya-coding** [comment]
Bonnes remarques Alexandre ! & merci Bastien

Nouveau draft :)
- Modification des noms
- Je pense qu'il faut laisser techno house car ca indique directement a la personne le type de musique, donc si tu kiffes, tu vas direct dessus, et si t'as pas kiffé la soirée, ba y'avais écris PARTOUT techno house
- J'ai rajouté quelques mots pour mieux expliquer le lieu et l'achat des places
- J'ai centré le triangle ucp (J'ai du ralonger la côté gauche Mdrr)
- J'ai ghetoizé et éclairci pour que ca tape à l'oeil
![draft2 copie](https://cloud.githubusercontent.com/assets/9800251/21393641/a44d0046-c795-11e6-8315-239f4bf5826d.jpg)

-

**Comment by AlexFourgs** [comment]
OH. JE KIFFE BIEN LA ! 

Pour moi c'est nickel, par contre met juste House dans ce cas parce que Cadence #1 c'est un event full house ;)

Et "place" prend un s je crois, je laisse les pros de la langue française confirmés.

En tout cas moi ça me convient bien :)

**Comment by Uinelj** [comment]
Superbe ! 
J'aime beaucoup, classieux et underground à la fois. 
Par contre, je me demande si c'est pertinent d'inscrire "House" sur l'affiche.. :)

**Comment by Eresia** [comment]
"Places disponibles" je suppose.

Sinon ça pète :D

**Comment by arya-coding** [comment]
Je mettrais au pluriel.

Après pour le "House", ca prenait du sens quand y'avais écris techno house, mais sachant que y'a que de la house, faut mettre que house, et mettre que "house" ca fait débile.

Vous pensez pas qu'il serait judicieux de mettre "Techno house", c'est vendeur sur une affiche et ce indique direct de quelle type de soirée ça parle

**Comment by Uinelj** [comment]
Ce que je vous propose à la rigueur c'est de faire un budget prévisionnel communication et on envoie le tout à Y en lui demandant son avis

**Comment by Uinelj** [comment]
![affiche](https://cloud.githubusercontent.com/assets/4410814/21452858/22dc4c12-c90a-11e6-8254-b5bffc1b59b3.png)

Niveau disposition j'imlaginais bien un truc du genre !

**Comment by AlexFourgs** [comment]
@aryus96 tu peux déjà mettre un premier nom d'artiste : "TAOS"
Si on booke tous les artistes qu'on veut, les artistes seront :
TAOS
Duvi
Marina Trench
G'Boï et Jean Mi

(Pas de fautes de frappes sur les noms d'artistes stp haha)

**Comment by akkes** [comment]
@aryus96 Tu pourras filer la source une fois fini?

**Comment by Uinelj** [comment]
Et ça serait cool d'avoir un devis soon :)

**Comment by arya-coding** [comment]
L'affiche est disponible via le lien suivant : https://www.aryaj.com/BDE
Il y a trois format : 
- JPG grosse qualité
- JPG qualité moyenne
- PNG

**Comment by akkes** [comment]
@aryus96 pas de source? 😞

**Comment by arya-coding** [comment]
Elle fait 1.5Go la source ... Mdr :/
Je maîtrise pas assez photoshop pour opti mes files etc, c'était pas une contrainte que j'avais avant

**Comment by akkes** [comment]
Bah il me faudrait au moins l'image de fond:
- je vais prendre le ciel comme fond fixe
- l'université sera en bas de la page

**Comment by AlexFourgs** [comment]
Les fichiers sont parfait en terme de taille / qualité pour l'impression.
Il faut juste rajouter un peu de marge sur les bords pour les logos au moment de la coupe afin d'être sûr qu'ils ne seront pas coupés etc...

**Comment by arya-coding** [comment]
@akkes J'ai rajouté les éléments que tu souhaitais. :)
@AlexFourgs  J'ai modifié les marges, le fichier est nommé "affiche2.jpg"

**Comment by akkes** [comment]
@aryus96 t'aurai la texture en non zoomé? ce serai 👌

**Comment by arya-coding** [comment]
Nouvelle version de l'affiche dispo au lien suivant : [www.aryaj.com/BDE/V2](www.aryaj.com/BDE/V2)
![affiche copie](https://cloud.githubusercontent.com/assets/9800251/21811814/46a28198-d751-11e6-9f39-875e4e0c31ef.jpg)
![affiche copi2e](https://cloud.githubusercontent.com/assets/9800251/21811815/46d46938-d751-11e6-9377-389cdbe208d9.jpg)

**Comment by AlexFourgs** [comment]
Putain à chaque fois que je la regarde je bande...
@aryus96 Magnifique, je sais pas quoi dire d'autre... Tu penses pouvoir faire une photo de couv' pour fb ? Comme ça on commence à communiquer un peu dessus. Genre à gauche tu met le truc multicolore ("logo") et à droite tu met "Cadence #1" + "Plus d'infos sur bdeecho.com" stp ? 

@akkes tu penses pouvoir adapter le site du coup ? Le fond du moins ou tu veux que j'essaie de le faire ?

**Comment by AlexFourgs** [comment]
Tout est clos ici :)
