### ISSUE TITLE
Trouver une nouvelle date pour Cadence #1

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#39]
Suite aux différentes réunions techniques et à la demande de subvention, nous devons trouver une nouvelle date rapidement pour l'événement, et ça ne peut être avant février.

* Vendredi 3 Février (un peu tôt à mon goût par rapport à la demande de sub vu qu'on sait pas quand ce sera voté)
* Vendredi 10 Février (optimal puisque c'est les vacances ce vendredi la, mais j'imagine qu'une soirée d'un autre BDE aura lieu)
* Vendredi 24 Février

**Comment by Eresia** [comment]
Pour l'instant on a pas de date pour Versity, mais je pense que je demanderais le 3 Février. L'avant vacances, c'est mort puisque c'est la veille des vacs et qu'on empiète sur le Samedi et le 24 je trouves ça tard. Mais bon, rien n'est fixé

**Comment by AlexFourgs** [comment]
@Uinelj ?

Plus vite on aura la nouvelle date, plus vite on pourra avancer.

Le 3 étant pour l'instant pour Versity.

**Comment by AlexFourgs** [comment]
10 Février pour l'instant. J'envoi un mail à la vie asso pour avoir confirmation que ça ne posera aucun problème.

**Comment by Eresia** [comment]
Février : Meilleur mois de l'année

**Comment by AlexFourgs** [comment]
C'est bon pour Cadence #1
