### ISSUE TITLE
Décider des dates pour les trois évènements

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#4]
Il faut décider des dates assez rapidement. Il y a plusieurs choses à prendre en compte, notamment : 
- La présence des gens à la fac. Faire un truc en Juin, quand tout le monde est en vacances.. Ou en révision..
- Les autres évènements parisiens house/techno. Personne veut voir des petites pointures quand en même temps t'as des gros noms sur paname.

**[MAJ 12/07/2016]**

Périodes des 3 Boilers :
- Octobre/Novembre
  - Vendredi 4 Novembre ? Vendredi de la semaine de rentrée de vacances.
- Janvier/Février
  - Vendredi 10 Février ? Vendredi de la veille des vacances. (Risqué, je pense qu'il va y avoir une soirée étudiante)
  - Vendredi 24 Février ? Vendredi de la rentrée des vacances. Si on choisis cette date ça permettra de rester dans une certaine logique de date vis à vis du premier événement.
- Mars/Avril/Mai
  - Vendredi 21 Avril ? Vendredi de la rentrée des vacances. On suit la logique des vendredi de rentrée du coup.

**Comment by AlexFourgs** [comment]
- Les autres associations aussi à prendre en compte.

Donc, il faut un calendrier des événements electro (Gros noms dans une boite comme festival, donc tout événements confondu) à Paris et ses alentours.

**Comment by AlexFourgs** [comment]
Je pense qu'il serait plus logique de se basé d'abord sur les autres associations pour fixer des dates provisoires ou des fourchettes de dates, et ensuite de vérifier si il n'y a pas d'autres événements externe à la fac dans ces périodes. Ce sera, d'après moi, plus simple de trouver des dates comme ça.

**Comment by AlexFourgs** [comment]
On fixe des dates provisoires pour les 3 événements avant la fin de semaine et on va commencer à parler budget pour chacun des événements (chacun étant particulier, et chaque budget sera redéfinit après chaque événement)

**Comment by AlexFourgs** [comment]
up, la logique entreprise pour l'instant est que les Boiler auront lieu les vendredi de rentrée de vacances.

Merci de confirmer rapidement les dates si elles vous conviennent, on pourra raviser plus tard si nécessaire.

**Comment by Uinelj** [comment]
Je valide ! 4 Novembre, 24 Février, 21 Avril :)

**Comment by AlexFourgs** [comment]
Je close l'issue, vous retrouverez toutes les informations ici : https://github.com/bdeecho/Chaudiere/blob/master/Boilers.md
