### ISSUE TITLE
Adapter dossier Cadence #1

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#40]
Adapter le dossier pour la demande de sub.

**Comment by AlexFourgs** [comment]
TODO : description réfléchi'son, bilan prévisionnel

+ adapter en dossier .pdf comme @akkes l'a fait la dernière fois.

**Comment by AlexFourgs** [comment]
Le dossier est finis : https://github.com/bdeecho/Chaudiere/blob/master/Cadence-1/dossier-cadence-1.md

@akkes je te laisse le refaire en pdf comme la dernière fois stp. Si tu vois quelques fautes n'hésite pas à corriger haha

**Comment by akkes** [comment]
[Cadence.pdf](https://github.com/bdeecho/Chaudiere/files/618958/Cadence.pdf)

Vérifiez que y'a bien tout et pas d'erreurs.

faut que je vous fasse un thème pour md histoire de pas avoir à recopier les tableaux une fois de plus.

**Comment by AlexFourgs** [comment]
@akkes Normalement c'est de nouveau bon.

J'ai retirer tout ce qui concernait l'événement dans le hall et réadapter les tableaux. J'ai ajouter des images aussi pour chaque presta.

**Comment by AlexFourgs** [comment]
https://github.com/bdeecho/Chaudiere/blob/master/Cadence-1/Dossier%20Cadence%20%231.pdf

C'est bon :)
