### ISSUE TITLE
Décider d'une stratégie de communication au vu des échéances.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#43]
La prochaine réunion technique n'aura pas lieu avec Janvier, soit __un mois__ avant la date de l'événement. De ce fait, on doit penser notre stratégie de communication.
Je un gros risque : 
- On risque de pas avoir le temps de toucher tout le public désiré

Ce risque risque d'engendrer moins de recettes, vu qu'on aura moins de places vendues, ce qui se ressentira sur le budget, déjà très serré. 

Donc deux solutions : 

- On prévoit le budget de façon à être rentable à partir d'un nombre moins important d'entrées (disons 300 au lieu de 450 par exemple)
- On augmente le budget/l'investissement communication : Des ads Facebook, du démarchage de BDE, d'Université, potentiellement des déplacements, tentatives d'interview Parisien/TRAX, etc.

Les deux solutions sont envisageables, l'une demandant un effort financier, l'autre un effort niveau effectif.

Je vous laisse en débattre..

**Comment by AlexFourgs** [comment]
D'après moi, il faut 5 à 6 semaines pour que la communication soit optimale :
* 1 semaine pour annoncer la nouvelle et faire du "bruit" sur l'ensemble du campus (affiche, événement fb, site, etc...)
* 1 semaine pour la pré-vente adhérents
* 3 semaines pour vendre tous les billets, communication massive sur tous les réseaux sociaux, annoncent de la line-up etc... LA TOTALE

Le problème qui se pose avec 300 personnes c'est qu'il faudra augmenter les prix des billets mais aussi les prix des consommations, il faudra combler le manque à gagner de 100 personnes soient ~1000€ pour la billetterie + ~700€ pour le bar soit un total de 1700€ à trouver sachant qu'il y a sûrement des dépenses qui vont apparaître qu'on a oublié.

 Une solution serait d'augmenter le billet d'entrée à 12€ et la pinte à 7€ (ça commence à faire chère la pinte)
