### ISSUE TITLE
Organiser un meetup avec Gabriel.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#7]
Gabriel est un ami qui est très intéressé par le projet Boiler et pourrait nous faire partager sa connaissance du milieu. Il dispose de contacts qui semblent aussi motivés, et il pourrait nous être d'une grande aide.

Il faudrait savoir quand on pourrait se rencontrer tous les 3, à minima.

**Comment by Eresia** [comment]
C'est Gabriel De Berranger ?

**Comment by Uinelj** [comment]
Nope, c'est un ami qui risque de beaucoup nous aider sur le projet.

**Comment by Eresia** [comment]
Ca marche

**Comment by Uinelj** [comment]
Du coup µCR pour toi Eresia, on a un contact avec un label parisien qui risque de nous rapporter beaucoup à différents niveaux :) ! Je ferai un point en réunion.

**Comment by Eresia** [comment]
Uh ?

**Comment by Uinelj** [comment]
Uh?

**Comment by Eresia** [comment]
Uh uh ?
