### ISSUE TITLE
Rendre les événements "Cadence" gratuit ?

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Chaudiere#8]

**Comment by Uinelj** [comment]
Idée intéressante.

Le + du payant, c'est d'alléger les subventions.
Le -, c'est que ça respecte moins la philosophie des boiler, de l'asso à son origine et de la fac en général, qui prône des idéaux d'accès pour tous.

**Comment by AlexFourgs** [comment]
Rien à rajouter, je pense que ce sera un point intéressant à aborder lors de la réunion.

Pour en revenir sur l’allègement des subventions : Présenter un événement de ce genre gratuit serait quasiment une première à l'Université, avec les bons contacts on pourra faire pencher la balance en notre faveur.

**Comment by AlexFourgs** [comment]
# A la suite de la réunion du 08/09/2016, nous avons convenu de fixer le prix de ces événements à 5€ avec une conso gratuite afin d'éviter les désistements sans désinscription.
