### ISSUE TITLE
Décider d'un ou de plusieurs plans pour le matériel.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Chaudiere#9]
C'est une étape très importante à statuer.

Est-ce qu'on propose un budget occasion aussi ?
## Sono

On loue en fonction de l'event.

| Type | Marque | Modèle | Neuf | Occasion | Features |
| --- | --- | --- | --- | --- | --- |
| Mix | Allen&Heath | Xone 43 | [695€](http://www.sonovente.com/allen-heath-xone-43-p47077.html) | [500€](http://fr.audiofanzine.com/console-dj-4-voies-ou-plus/allen-heath/xone-43/petites-annonces/) | 4 voies |
| Mix | Allen&Heath | Xone 43 C | [795€](http://www.sonovente.com/allen-heath-xone-43c-p47392.html) |  | \+ Serato |
| Mix | Allen&Heath | Xone 92 | [1125€](http://www.sonovente.com/allen-heath-xone-92-p16635.html) | [700-900€](http://fr.audiofanzine.com/console-dj-4-voies-ou-plus/allen-heath/xone-92/petites-annonces/) | 6 voies (4+2Mic), MIDI, LFO, VCF |
| Mix | Pioneer | DJM 350 | [489€](http://www.sonovente.com/pioneer-djm-350-p23794.html) | [250-300€](http://fr.audiofanzine.com/console-dj-2-voies/pioneer/djm-350/petites-annonces/) | 2 voies, 4 FX |
| Mix | Pioneer | DJM 750K | [918€](http://www.sonovente.com/pioneer-djm-750-k-p39545.html) | [650-700€](http://fr.audiofanzine.com/console-dj-4-voies-ou-plus/pioneer/djm-750-k/petites-annonces/) | 4 voies, multiFX |
| Mix | Pioneer | DJM 850K | [1499€](http://www.sonovente.com/pioneer-djm-850-k-p34040.html) | [800€](http://fr.audiofanzine.com/console-dj-4-voies-ou-plus/pioneer/djm-850-k/petites-annonces/) | 4 voies, Noise, Gate, Beat, comp. Traktor (timecode) |
| PlatCD | Pioneer | CDJ 850 |  |  |  |
| PlatMP3 | Pioneer | XDJ 700 |  |  |  |
| PlatMP3 | Pioneer | XDJ 1000 |  |  |  |
| PlatVin | Technics | SL-1210 |  |  |  |
| PlatVin | Stanton | ST-150 |  |  |  |
|  |  |  |  |  |  |

**Comment by AlexFourgs** [comment]
Problème réglé, on verra à la subvention.
